export const spider = [
  {
    id: "jekko",
    brandName: "Jekko",
    equipments: [
      {
        modelName: "SPX312",
        weight: "1915kg",
        weightWithJib: "1985kg",
        maxHeight: "10.9m",
        maxLength: "9.5m",
        maxSafeLoad: "1200kg",
        maxLoad1Line: "600kg",
        maxLoad2Lines: "1200kg",
        maxLoad3Lines: null,
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "3760mm x 3760mm",
        maxOutriggerLoad: "1850kg",
        operationType: "배터리",
        brochurePdf: "/equipment/spider/Jekko/SPX312/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Jekko/SPX312/technical-data.pdf"
      },
      {
        modelName: "SPX328",
        weight: "2300kg",
        weightWithJib: "2450kg",
        maxHeight: "12.8m",
        maxLength: "10.4m",
        maxSafeLoad: "2800kg",
        maxLoad1Line: "700kg",
        maxLoad2Lines: "1400kg",
        maxLoad3Lines: null,
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "3822mm x 3861mm",
        maxOutriggerLoad: "2100kg",
        operationType: "배터리",
        brochurePdf: "/equipment/spider/Jekko/SPX328/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Jekko/SPX328/technical-data.pdf"
      },
      {
        modelName: "SPX424",
        weight: "2195kg",
        weightWithJib: "2370kg",
        maxHeight: "15.2m",
        maxLength: "11.8m",
        maxSafeLoad: "2400kg",
        maxLoad1Line: "800kg",
        maxLoad2Lines: "1600kg",
        maxLoad3Lines: "2400kg",
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "3730mm x 3730mm",
        maxOutriggerLoad: "2200kg",
        operationType: "배터리",
        brochurePdf: "/equipment/spider/Jekko/SPX424/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Jekko/SPX424/technical-data.pdf"
      },
      {
        modelName: "SPX527",
        weight: "3660kg",
        weightWithJib: "3870kg",
        maxHeight: "18.3m",
        maxLength: "11.2m",
        maxSafeLoad: "2700kg",
        maxLoad1Line: "900kg",
        maxLoad2Lines: "1800kg",
        maxLoad3Lines: "2700kg",
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "4160mm x 4160mm",
        maxOutriggerLoad: "2700kg",
        operationType: "디젤(경유) 20L",
        brochurePdf: "/equipment/spider/Jekko/SPX527/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Jekko/SPX527/technical-data.pdf"
      },
      {
        modelName: "SPX532",
        weight: "2560kg",
        weightWithJib: "2760kg",
        maxHeight: "17.3m",
        maxLength: "14.8m",
        maxSafeLoad: "3200kg",
        maxLoad1Line: "800kg",
        maxLoad2Lines: "1600kg",
        maxLoad3Lines: "3200kg",
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "4400mm x 4400mm",
        maxOutriggerLoad: "3000kg",
        operationType: "배터리",
        brochurePdf: "/equipment/spider/Jekko/SPX532/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Jekko/SPX532/technical-data.pdf"
      },
      {
        modelName: "SPX1040",
        weight: "6400kg",
        weightWithJib: "6710kg",
        maxHeight: "23.5m",
        maxLength: "14.5m",
        maxSafeLoad: "4000kg",
        maxLoad1Line: "1000kg",
        maxLoad2Lines: "2000kg",
        maxLoad3Lines: "3000kg",
        maxLoad4Lines: "4000kg",
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "4169mm x 4170mm",
        maxOutriggerLoad: "4500kg",
        operationType: "디젤(경유) 20L",
        brochurePdf: "/equipment/spider/Jekko/SPX1040/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Jekko/SPX1040/technical-data.pdf"
      },
      {
        modelName: "SPX650",
        weight: "5962kg",
        weightWithJib: "6372kg",
        maxHeight: "23.5m",
        maxLength: "20m",
        maxSafeLoad: "5000kg",
        maxLoad1Line: "800kg",
        maxLoad2Lines: "1600kg",
        maxLoad3Lines: "2400kg",
        maxLoad4Lines: "3200kg",
        maxLoad5Lines: "4000kg",
        maxLoad6Lines: "4800kg",
        outriggerWidth: "4500mm x 4500mm",
        maxOutriggerLoad: "4800kg",
        operationType: "배터리",
        brochurePdf: "/equipment/spider/Jekko/SPX650/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Jekko/SPX650/technical-data.pdf"
      },
      {
        modelName: "JF545",
        weight: "17250kg",
        weightWithJib: "18450kg",
        maxHeight: "32.5m",
        maxLength: "28m",
        maxSafeLoad: "15500kg",
        maxLoad1Line: "2600kg",
        maxLoad2Lines: "4000kg",
        maxLoad3Lines: "6000kg",
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "6730mm x 6720mm",
        maxOutriggerLoad: "11250kg",
        operationType: "디젤(경유) 20L",
        brochurePdf: "/equipment/spider/Jekko/JF545/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Jekko/JF545/technical-data.pdf"
      }
    ]
  },
  {
    id: "hoeflon",
    brandName: "Hoeflon",
    equipments: [
      {
        modelName: "C1",
        weight: "1060kg",
        weightWithJib: null,
        maxHeight: "5.7m",
        maxLength: "4.6m",
        maxSafeLoad: "550kg",
        maxLoad1Line: "550kg",
        maxLoad2Lines: null,
        maxLoad3Lines: null,
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "1478mm x 1100mm",
        maxOutriggerLoad: null,
        operationType: "배터리",
        brochurePdf: "/equipment/spider/Hoeflon/C1/brochure.pdf",
        technicalDataPdf: "/equipment/spider/Hoeflon/C1/technical-data.pdf"
      },
      {
        modelName: "C6",
        weight: "2650kg",
        weightWithJib: "2850kg",
        maxHeight: "15.8m",
        maxLength: "13.7m",
        maxSafeLoad: "3000kg",
        maxLoad1Line: "1000kg",
        maxLoad2Lines: "2000kg",
        maxLoad3Lines: null,
        maxLoad4Lines: "4000kg",
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "4200mm x 4400mm",
        maxOutriggerLoad: "2800kg",
        operationType: "배터리/디젤(경유) 20L",
        brochurePdf: "/equipment/spider/Hoeflon/C6/brochure.pdf",
        technicalDataPdf: null
      },
      {
        modelName: "C10",
        weight: "4400kg",
        weightWithJib: "4700kg",
        maxHeight: "22m",
        maxLength: "19.8m",
        maxSafeLoad: "4000kg",
        maxLoad1Line: "1000kg",
        maxLoad2Lines: "2000kg",
        maxLoad3Lines: null,
        maxLoad4Lines: "4000kg",
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "4578mm x 4578mm",
        maxOutriggerLoad: "4500kg",
        operationType: "배터리/디젤(경유) 20L",
        brochurePdf: "/equipment/spider/Hoeflon/C10/brochure.pdf",
        technicalDataPdf: null
      }
    ]
  },
  {
    id: "befard",
    brandName: "BEFARD",
    equipments: [
      {
        modelName: "XM800",
        weight: "1150kg",
        weightWithJib: null,
        maxHeight: "6.17m",
        maxLength: "5m",
        maxSafeLoad: "800kg",
        maxLoad1Line: "500kg",
        maxLoad2Lines: "800kg",
        maxLoad3Lines: null,
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "2251mm x 1459mm",
        maxOutriggerLoad: null,
        operationType: "배터리",
        brochurePdf: "/equipment/spider/BEFARD/XM800/brochure.pdf",
        technicalDataPdf: null
      },
      {
        modelName: "XGR800",
        weight: "1600kg",
        weightWithJib: null,
        maxHeight: "5.5m",
        maxLength: "3.5m",
        maxSafeLoad: "800kg",
        maxLoad1Line: null,
        maxLoad2Lines: null,
        maxLoad3Lines: null,
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "2800mm x 1600mm",
        maxOutriggerLoad: null,
        operationType: "배터리",
        brochurePdf: "/equipment/spider/BEFARD/XGR800/brochure.pdf",
        technicalDataPdf: null
      }
    ]
  },
  {
    id: "unic",
    brandName: "UNIC",
    equipments: [
      {
        modelName: "URW295C",
        weight: "2040kg",
        weightWithJib: null,
        maxHeight: "8.8m",
        maxLength: "8.41m",
        maxSafeLoad: "2900kg",
        maxLoad1Line: "700kg",
        maxLoad2Lines: "1400kg",
        maxLoad3Lines: "2900kg",
        maxLoad4Lines: null,
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "3885mm x 3935mm",
        maxOutriggerLoad: null,
        operationType: "가솔린(휘발유) 6L",
        brochurePdf: "/equipment/spider/UNIC/URW295C/brochure.pdf",
        technicalDataPdf: null
      },
      {
        modelName: "URW546",
        weight: "4920kg",
        weightWithJib: null,
        maxHeight: "16m",
        maxLength: "15.5m",
        maxSafeLoad: "4000kg",
        maxLoad1Line: "1000kg",
        maxLoad2Lines: "2000kg",
        maxLoad3Lines: null,
        maxLoad4Lines: "4000kg",
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "5900mm x 5940mm",
        maxOutriggerLoad: null,
        operationType: "디젤(경유) 40L",
        brochurePdf: "/equipment/spider/UNIC/URW546/brochure.pdf",
        technicalDataPdf: null
      },
      {
        modelName: "URW547C",
        weight: "5170kg",
        weightWithJib: null,
        maxHeight: "18.2m",
        maxLength: "17.8m",
        maxSafeLoad: "4000kg",
        maxLoad1Line: "1000kg",
        maxLoad2Lines: "2000kg",
        maxLoad3Lines: null,
        maxLoad4Lines: "4000kg",
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "5900mm x 5940mm",
        maxOutriggerLoad: null,
        operationType: "디젤(경유) 40L",
        brochurePdf: "/equipment/spider/UNIC/URW547C/brochure.pdf",
        technicalDataPdf: null
      },
      {
        modelName: "URW706C",
        weight: "8080kg",
        weightWithJib: null,
        maxHeight: "25.9m",
        maxLength: "20m",
        maxSafeLoad: "6000kg",
        maxLoad1Line: "1500kg",
        maxLoad2Lines: "3000kg",
        maxLoad3Lines: null,
        maxLoad4Lines: "6000kg",
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "6550mm x 6460mm",
        maxOutriggerLoad: null,
        operationType: "디젤(경유) 60L",
        brochurePdf: "/equipment/spider/UNIC/URW706C/brochure.pdf",
        technicalDataPdf: null
      }
    ]
  },
  {
    id: "maeda",
    brandName: "MAEDA",
    equipments: [
      {
        modelName: "MC305",
        weight: "4080kg",
        weightWithJib: null,
        maxHeight: "12.5m",
        maxLength: "12.1m",
        maxSafeLoad: "2980kg",
        maxLoad1Line: "750kg",
        maxLoad2Lines: "1480kg",
        maxLoad3Lines: null,
        maxLoad4Lines: "2900kg",
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "4888mm x 4504mm",
        maxOutriggerLoad: "1010kg",
        operationType: "디젤(경유) 40L",
        brochurePdf: "/equipment/spider/MAEDA/MC305/brochure.pdf",
        technicalDataPdf: null
      },
      {
        modelName: "MC405",
        weight: "5750kg",
        weightWithJib: null,
        maxHeight: "16.8m",
        maxLength: "16m",
        maxSafeLoad: "3830kg",
        maxLoad1Line: "1000kg",
        maxLoad2Lines: "2000kg",
        maxLoad3Lines: null,
        maxLoad4Lines: "4000kg",
        maxLoad5Lines: null,
        maxLoad6Lines: null,
        outriggerWidth: "5785mm x 5520mm",
        maxOutriggerLoad: "1400kg",
        operationType: "디젤(경유) 60L",
        brochurePdf: "/equipment/spider/MAEDA/MC405/brochure.pdf",
        technicalDataPdf: null
      }
    ]
  }
];
