export const dictionaries = {
  modelName: "모델명",
  dimensions: "치수 (LxWxH)",
  bodyWeight: "차체 무게",
  dryWeight: "건조 무게 (드라이 웨이트)",
  counterWeight: "카운터 웨이트",
  maxSafeLoad: "최대 안전하중",
  maxLiftingHeight: "최대 인양높이",
  maxLiftingLength: "최대 인양길이",
  maxHeightTipLoadWinch: "최대 높이 끝단 하중 (윈치)",
  maxLengthTipLoadWinch: "최대 길이 끝단 하중 (윈치)",
  maxHeightTipLoadHook: "최대 높이 끝단 하중 (후크)(집게)(패드)",
  maxLengthTipLoadHook: "최대 길이 끝단 하중 (후크)(집게)(패드)",
  workingAngle: "작업 각도",
  hoistingSpeed: "권상 속도",
  slewingAngle: "선회 각도",
  slewingSpeed: "선회 속도",
  winchLength: "윈치 길이",
  winchDiameter: "윈치 두께 (⌀ = 직경)",
  outriggerExtensionDimensions: "아웃트리거 확장 치수",
  maxOutriggerLoad: "최대아웃트리거하중",
  trackDimensions: "트랙 치수(확장)",
  speed: "속력 1단, (2단)",
  climbingAbility: "등판 능력",
  groundPressure: "접지압",
  operatingMethod: "작동방식",
  powerType: "엔진/배터리 (HP : 마력)",
  powerPack: "파워팩",
  powerSupply: "사용 전원",
  additionalOptions: "추가 옵션"
};

export const craneType = {
  jib: "보조붐",
  grapple: "집게",
  glass: "유리흡착기",
  crawler: "크롤러"
} as const;

export type AccessoryType = keyof typeof craneType;

export type Accessory = {
  accessoryName: string; // 악세서리명
  accessoryType: AccessoryType; // 악세서리 타입
  dimensions: string; // 치수 (LxWxH)
  bodyWeight: string; // 차체 무게
  dryWeight: string; // 건조 무게 (드라이 웨이트)
  counterWeight: string; // 카운터 웨이트
  maxSafeLoad: string; // 최대 안전하중
  maxLiftingHeight: string; // 최대 인양높이
  maxLiftingLength: string; // 최대 인양길이
  maxHeightTipLoadWinch: string; // 최대 높이 끝단 하중 (윈치)
  maxLengthTipLoadWinch: string; // 최대 길이 끝단 하중 (윈치)
  maxHeightTipLoadHook: string; // 최대 높이 끝단 하중 (후크)(집게)(패드)
  maxLengthTipLoadHook: string; // 최대 길이 끝단 하중 (후크)(집게)(패드)
  workingAngle: string; // 작업 각도
  hoistingSpeed: string; // 권상 속도
  slewingAngle: string; // 선회 각도
  slewingSpeed: string; // 선회 속도
  winchLength: string; // 윈치 길이
  winchDiameter: string; // 윈치 두께 (⌀ = 직경)
  outriggerExtensionDimensions: string; // 아웃트리거 확장 치수
  maxOutriggerLoad: string; // 최대아웃트리거하중
  trackDimensions: string; // 트랙 치수(확장)
  speed: string; // 속력 1단, (2단)
  climbingAbility: string; // 등판 능력
  groundPressure: string; // 접지압
  operatingMethod: string; // 작동방식
  powerType: string; // 엔진/배터리 (HP : 마력)
  powerPack: string; // 파워팩
  powerSupply: string; // 사용 전원
  additionalOptions: string; // 추가 옵션
};

export type Equipment = {
  modelName: string; // 모델명
  dimensions: string; // 치수 (LxWxH)
  bodyWeight: string; // 차체 무게
  dryWeight: string; // 건조 무게 (드라이 웨이트)
  counterWeight: string; // 카운터 웨이트
  maxSafeLoad: string; // 최대 안전하중
  maxLiftingHeight: string; // 최대 인양높이
  maxLiftingLength: string; // 최대 인양길이
  maxHeightTipLoadWinch: string; // 최대 높이 끝단 하중 (윈치)
  maxLengthTipLoadWinch: string; // 최대 길이 끝단 하중 (윈치)
  maxHeightTipLoadHook: string; // 최대 높이 끝단 하중 (후크)(집게)(패드)
  maxLengthTipLoadHook: string; // 최대 길이 끝단 하중 (후크)(집게)(패드)
  workingAngle: string; // 작업 각도
  hoistingSpeed: string; // 권상 속도
  slewingAngle: string; // 선회 각도
  slewingSpeed: string; // 선회 속도
  winchLength: string; // 윈치 길이
  winchDiameter: string; // 윈치 두께 (⌀ = 직경)
  outriggerExtensionDimensions: string; // 아웃트리거 확장 치수
  maxOutriggerLoad: string; // 최대아웃트리거하중
  trackDimensions: string; // 트랙 치수(확장)
  speed: string; // 속력 1단, (2단)
  climbingAbility: string; // 등판 능력
  groundPressure: string; // 접지압
  operatingMethod: string; // 작동방식
  powerType: string; // 엔진/배터리 (HP : 마력)
  powerPack: string; // 파워팩
  powerSupply: string; // 사용 전원
  additionalOptions: string; // 추가 옵션
  isBrochure: boolean;
  isTechnicalData: boolean;
  accessories?: Accessory[];
  description?: string;
};

export type Brand = {
  brandName: string;
  equipments: Equipment[];
};

export type CraneType = {
  type: string;
  brands: Brand[];
};

export const cranes: CraneType[] = [
  {
    type: "spider",
    brands: [
      {
        brandName: "Jekko",
        equipments: [
          {
            modelName: "SPX312",
            dimensions: "2790 x 770 x 1600mm",
            bodyWeight: "1915kg",
            dryWeight: "1800kg",
            counterWeight: "",
            maxSafeLoad: "1200kg",
            maxLiftingHeight: "7.6m",
            maxLiftingLength: "7.3m",
            maxHeightTipLoadWinch: "600kg",
            maxLengthTipLoadWinch: "300kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 75°",
            hoistingSpeed: "15.1 ~ 31.8m/min",
            slewingAngle: "330°",
            slewingSpeed: "1.0rpm",
            winchLength: "63m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "3700 x 3700mm",
            maxOutriggerLoad: "1850kg",
            trackDimensions: "770, (1065)mm",
            speed: "0.85km/h",
            climbingAbility: "20°",
            groundPressure: "0.44kg/㎠",
            operatingMethod: "배터리",
            powerType: "24V 240Ah\n(12V 120Ah) x 2\n24V - 3F 4.0kW 5.5HP",
            powerPack: "4.0kW 220VAC 50Hz",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "2790 x 770 x 1600mm",
                bodyWeight: "1915 + 85kg\n(2000kg)",
                dryWeight: "1800kg",
                counterWeight: "",
                maxSafeLoad: "1200kg",
                maxLiftingHeight: "9.8m",
                maxLiftingLength: "9.6m",
                maxHeightTipLoadWinch: "400kg",
                maxLengthTipLoadWinch: "100kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75°",
                hoistingSpeed: "15.1 ~ 31.8m/min",
                slewingAngle: "330°",
                slewingSpeed: "1.0rpm",
                winchLength: "63m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "3700 x 3700mm",
                maxOutriggerLoad: "1850kg",
                trackDimensions: "775, (1065)mm",
                speed: "0.85km/h",
                climbingAbility: "20°",
                groundPressure: "0.44kg/㎠",
                operatingMethod: "배터리",
                powerType: "24V 240Ah\n(12V 120Ah) x 2\n24V - 3F 4.0kW 5.5HP",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "400.1MX",
                accessoryType: "jib"
              }
            ],
            description:
              "SPX312는 작고 컴팩트한 디자인과 자국을 남기지 않는 흰색 트랙, 친환경적인 리튬 배터리. 그리고 0.44kg/cm2의 낮은 트랙 압력을 갖춰 평범한 크레인과 리프팅 장비로는 감당할 수 없는 장소와 각종 민감하고 복잡한 실내에서의 작업에 쓸 수 있는 완벽한 파트너입니다."
          },
          {
            modelName: "SPX328",
            dimensions: "2950 x 730 x 1610mm",
            bodyWeight: "2300kg",
            dryWeight: "2300kg",
            counterWeight: "",
            maxSafeLoad: "2800kg",
            maxLiftingHeight: "10.4m",
            maxLiftingLength: "8m",
            maxHeightTipLoadWinch: "1020kg",
            maxLengthTipLoadWinch: "250kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-4.5° ~ 77°",
            hoistingSpeed: "38 ~ 53m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.2rpm",
            winchLength: "62m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "3830 x 3865mm",
            maxOutriggerLoad: "2100kg",
            trackDimensions: "730mm",
            speed: "1.2km/h, (2.6km/h)",
            climbingAbility: "12°",
            groundPressure: "0.62kg/㎠",
            operatingMethod: "리튬 배터리",
            powerType: "48V 250Ah",
            powerPack: "",
            powerSupply: "1.0kW 220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "2950 x 730 x 1610mm",
                bodyWeight: "2420kg",
                dryWeight: "2300kg",
                counterWeight: "",
                maxSafeLoad: "2800kg",
                maxLiftingHeight: "12.8m",
                maxLiftingLength: "10.4m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "300kg",
                maxLengthTipLoadHook: "100kg",
                workingAngle: "-4.5° ~ 77°",
                hoistingSpeed: "38 ~ 53m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "62m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "3830 x 3865mm",
                maxOutriggerLoad: "2100kg",
                trackDimensions: "730mm",
                speed: "1.2km/h, (2.6km/h)",
                climbingAbility: "12°",
                groundPressure: "0.62kg/㎠",
                operatingMethod: "리튬 배터리",
                powerType: "48V 250Ah",
                powerPack: "",
                powerSupply: "1.0kW 220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "JIB 500.1EX",
                accessoryType: "jib"
              }
            ],
            description:
              "Jekko SPX328은 2,800kg의 리프팅 용량을 갖춘 컴팩트하고 강력한 친환경 미니 크레인입니다. 폭이 730mm에 불과하기 때문에 다른 크레인이라면 상상조차 할 수 없는 좁은 곳으로도 들어갈 수 있죠. 거기에 더하여 리튬 배터리로 작동하기 때문에 최고의 성능과 무공해를 자랑하여 복잡한 실내 및 민감한 작업 환경에 가장 적합하죠."
          },
          {
            modelName: "SPX424",
            dimensions: "3165 x 775 x 1955mm",
            bodyWeight: "2195kg",
            dryWeight: "2080kg",
            counterWeight: "",
            maxSafeLoad: "2400kg",
            maxLiftingHeight: "8.5m",
            maxLiftingLength: "7.6m",
            maxHeightTipLoadWinch: "1000kg",
            maxLengthTipLoadWinch: "400kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 75°",
            hoistingSpeed: "26 ~ 31.8m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.5rpm",
            winchLength: "73m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "3730 x 3730mm",
            maxOutriggerLoad: "2200kg",
            trackDimensions: "775, (1100)mm",
            speed: "0.72km/h",
            climbingAbility: "20°",
            groundPressure: "0.55kg/㎠",
            operatingMethod: "배터리",
            powerType: "24V 240Ah\n24V - 3F 4.0kW 5.5HP",
            powerPack: "4.0kW 220VAC 50Hz",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "3165 x 775 x 1955mm",
                bodyWeight: "2195 + 170kg\n(2365kg)",
                dryWeight: "2080kg",
                counterWeight: "",
                maxSafeLoad: "2400kg",
                maxLiftingHeight: "13.49m",
                maxLiftingLength: "11.8m",
                maxHeightTipLoadWinch: "300kg",
                maxLengthTipLoadWinch: "110kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75°",
                hoistingSpeed: "26 ~ 31.8m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.5rpm",
                winchLength: "73m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "3730 x 3730mm",
                maxOutriggerLoad: "2200kg",
                trackDimensions: "775, (1100)mm",
                speed: "0.72km/h",
                climbingAbility: "20°",
                groundPressure: "0.55kg/㎠",
                operatingMethod: "배터리",
                powerType: "24V 240Ah\n24V - 3F 4.0kW 5.5HP",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB800.2H1MX",
                accessoryType: "jib"
              },
              {
                dimensions: "3165 x 775 x 1955mm",
                bodyWeight: "2195 + 295kg\n(2490kg)",
                dryWeight: "2080kg",
                counterWeight: "",
                maxSafeLoad: "10패드 800kg",
                maxLiftingHeight: "9.8m",
                maxLiftingLength: "7m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "700kg",
                maxLengthTipLoadHook: "140kg",
                workingAngle: "0° ~ 75°\n(↑90° ↓45°)\n(← 90° 90°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.5rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "3730 x 3730mm",
                maxOutriggerLoad: "2200kg",
                trackDimensions: "775, (1100)mm",
                speed: "0.72km/h",
                climbingAbility: "20°",
                groundPressure: "0.55kg/㎠",
                operatingMethod: "배터리",
                powerType: "24V 240Ah\n24V - 3F 4.0kW 5.5HP",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "MR800.4",
                accessoryType: "glass"
              }
            ],
            description:
              "Jekko에서 제작한 크레인의 대표 모델 중 하나인 SPX424는 리튬 배터리로 움직이는 거미크레인 시장에서 가장 인기 있는 제품 중 하나입니다. Jekko의 기술, 혁신, 그리고 신뢰성이 이 작은 크기의 역사상 가장 많이 팔린 베스트셀러 크레인에 모두 담겨 있죠."
          },
          {
            modelName: "SPX527",
            dimensions: "4145 x 1100 x 1957mm",
            bodyWeight: "3660kg",
            dryWeight: "3600kg",
            counterWeight: "",
            maxSafeLoad: "2700kg",
            maxLiftingHeight: "12.1m",
            maxLiftingLength: "11m",
            maxHeightTipLoadWinch: "1000kg",
            maxLengthTipLoadWinch: "250kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-2° ~ 80°",
            hoistingSpeed: "40.6m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "60m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4160 x 4160mm",
            maxOutriggerLoad: "2700kg",
            trackDimensions: "600, (1100)mm",
            speed: "2.0km/h",
            climbingAbility: "25°",
            groundPressure: "0.53kg/㎠",
            operatingMethod: "디젤(경유) 20L",
            powerType: "KUBOTA D1105-E3B\n(18.5kW 25HP)",
            powerPack: "4.0kW 220VAC 50Hz",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "4145 x 1100 x 1957mm",
                bodyWeight: "3660 + 215kg\n(3875kg)",
                dryWeight: "3600kg",
                counterWeight: "",
                maxSafeLoad: "2700kg",
                maxLiftingHeight: "16.3m",
                maxLiftingLength: "11m",
                maxHeightTipLoadWinch: "500kg",
                maxLengthTipLoadWinch: "190kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "-2° ~ 80°",
                hoistingSpeed: "40.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "60m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4160 x 4160mm",
                maxOutriggerLoad: "2700kg",
                trackDimensions: "600, (1100)mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.53kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA D1105-E3B\n(18.5kW 25HP)",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 600.2H",
                accessoryType: "jib"
              },
              {
                dimensions: "4145 x 1100 x 1957mm",
                bodyWeight: "3660 + 295kg\n(3955kg)",
                dryWeight: "3600kg",
                counterWeight: "",
                maxSafeLoad: "10패드 800kg",
                maxLiftingHeight: "13.4m",
                maxLiftingLength: "9m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "600kg",
                maxLengthTipLoadHook: "150kg",
                workingAngle: "-2° ~ 80°\n(↑90° ↓45°)\n(← 90° 90°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4160 x 4160mm",
                maxOutriggerLoad: "2700kg",
                trackDimensions: "600, (1100)mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.53kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA D1105-E3B\n(18.5kW 25HP)",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "MR800.4",
                accessoryType: "glass"
              }
            ],
            description:
              "Jekko SPX 527은 작고 컴팩트한 디자인과 강력한 디젤 엔진을 갖춘 미니 크레인으로 실외 실내를 가리지 않습니다. 거기에 더하여 전선으로 연결하여 전기로 작동할 수 있도록 설계가 되어있어, 실내에서의 작업에선 공해도 일으키지 않죠. "
          },
          {
            modelName: "SPX532",
            dimensions: "3220 x 770 x 1950mm",
            bodyWeight: "2560kg",
            dryWeight: "2520kg",
            counterWeight: "200kg",
            maxSafeLoad: "3200kg",
            maxLiftingHeight: "12.1m",
            maxLiftingLength: "9.5m",
            maxHeightTipLoadWinch: "1450kg",
            maxLengthTipLoadWinch: "470kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 83°",
            hoistingSpeed: "40.6m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.2rpm",
            winchLength: "60m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "4400 x 4400mm",
            maxOutriggerLoad: "3000kg",
            trackDimensions: "770, (1050)mm",
            speed: "2.7km/h",
            climbingAbility: "20°",
            groundPressure: "0.63kg/㎠",
            operatingMethod: "리튬 배터리",
            powerType: "24V 300Ah\n(24V - 3F 5.5kW 7.5HP)",
            powerPack: "",
            powerSupply: "7.7kW 220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "3220 x 770 x 1950mm",
                bodyWeight: "2770kg",
                dryWeight: "2520kg",
                counterWeight: "200kg",
                maxSafeLoad: "3200kg",
                maxLiftingHeight: "17.3m",
                maxLiftingLength: "14.8m",
                maxHeightTipLoadWinch: "400kg",
                maxLengthTipLoadWinch: "100kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 83°",
                hoistingSpeed: "40.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "60m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "4400 x 4400mm",
                maxOutriggerLoad: "3000kg",
                trackDimensions: "770, (1050)mm",
                speed: "2.7km/h",
                climbingAbility: "20°",
                groundPressure: "0.63kg/㎠",
                operatingMethod: "리튬 배터리",
                powerType: "24V 300Ah\n(24V - 3F 5.5kW 7.5HP)",
                powerPack: "",
                powerSupply: "7.7kW 220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "JIB1000.2H1MX",
                accessoryType: "jib"
              },
              {
                dimensions: "3220 x 770 x 1950mm",
                bodyWeight: "2560 + 230kg\n(2790kg)",
                dryWeight: "2520kg",
                counterWeight: "",
                maxSafeLoad: "500kg",
                maxLiftingHeight: "13.6m",
                maxLiftingLength: "10m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "500kg",
                maxLengthTipLoadHook: "200kg",
                workingAngle: "0° ~ 83°\n(↑ 91° ↓ 92°)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4400 x 4400mm",
                maxOutriggerLoad: "3000kg",
                trackDimensions: "770, (1050)mm",
                speed: "2.7km/h",
                climbingAbility: "20°",
                groundPressure: "0.63kg/㎠",
                operatingMethod: "리튬 배터리",
                powerType: "24V 300Ah\n(24V - 3F 5.5kW 7.5HP)",
                powerPack: "",
                powerSupply: "7.7kW 220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "JIB500GR",
                accessoryType: "grapple"
              }
            ],
            description:
              "SPX532는 좁은 공간에서도 최대 성능을 발휘하도록 설계된 Jekko의 최첨단 거미크레인입니다. 최대 3,200kg의 인양력과 지브를 사용할 경우 17.3m까지 도달할 수 있는 이 거미크레인은 건설부터 산업 유지 보수까지 다양한 분야에서 강력한 성능, 정밀성, 그리고 다재다능함을 자랑하죠. 거기에 더하여 리튬 배터리를 사용하여 무공해 기능을 갖추고 있어 실내 및 민감한 환경에 이상적입니다."
          },
          {
            modelName: "SPX1040",
            dimensions: "5390 x 1450 x 2040mm",
            bodyWeight: "6400kg",
            dryWeight: "6300kg",
            counterWeight: "760kg",
            maxSafeLoad: "4000kg",
            maxLiftingHeight: "14.5m",
            maxLiftingLength: "13m",
            maxHeightTipLoadWinch: "1800kg",
            maxLengthTipLoadWinch: "550kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-4° ~ 80°",
            hoistingSpeed: "50.6m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "125m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4200 x 4200mm",
            maxOutriggerLoad: "4500kg",
            trackDimensions: "1450mm",
            speed: "2.0km/h",
            climbingAbility: "25°",
            groundPressure: "0.59kg/㎠",
            operatingMethod: "디젤(경유) 20L",
            powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
            powerPack: "8.0kW 220VAC 60Hz",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "5390 x 1450 x 2040mm",
                bodyWeight: "6400 + 210kg\n(6610kg)",
                dryWeight: "6300kg",
                counterWeight: "760kg",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "18.6m",
                maxLiftingLength: "13m",
                maxHeightTipLoadWinch: "900kg",
                maxLengthTipLoadWinch: "100kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "-4° ~ 80°",
                hoistingSpeed: "50.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "125m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "1450mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.59kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
                powerPack: "8.0kW 220VAC 60Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 600.2H",
                accessoryType: "jib"
              },
              {
                dimensions: "5390 x 1450 x 2040mm",
                bodyWeight: "6400 + 70kg\n(6470kg)",
                dryWeight: "6300kg",
                counterWeight: "760kg",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "16.1m",
                maxLiftingLength: "14.5m",
                maxHeightTipLoadWinch: "1600kg",
                maxLengthTipLoadWinch: "300kg",
                maxHeightTipLoadHook: "1600kg",
                maxLengthTipLoadHook: "300kg",
                workingAngle: "-4° ~ 80°",
                hoistingSpeed: "50.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "125m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "1450mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.59kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
                powerPack: "8.0kW 220VAC 60Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 3500G",
                accessoryType: "jib"
              },
              {
                dimensions: "5390 x 1450 x 2040mm",
                bodyWeight: "6400 + 210kg\n(6610kg)",
                dryWeight: "6300kg",
                counterWeight: "760kg",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "23.5m",
                maxLiftingLength: "13m",
                maxHeightTipLoadWinch: "800kg",
                maxLengthTipLoadWinch: "300kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "-4° ~ 80°",
                hoistingSpeed: "50.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "125m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "1450mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.59kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
                powerPack: "8.0kW 220VAC 60Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 100.1FL",
                accessoryType: "jib"
              },
              {
                dimensions: "5390 x 1450 x 2040mm",
                bodyWeight: "6400 + 295kg\n(6695kg)",
                dryWeight: "6300kg",
                counterWeight: "760kg",
                maxSafeLoad: "800kg",
                maxLiftingHeight: "16.3m",
                maxLiftingLength: "13m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "800kg",
                maxLengthTipLoadHook: "150kg",
                workingAngle: "-4° ~ 80°\n(↑90° ↓45°)\n(← 90° 90°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4200 x 4200mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "1450mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.59kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
                powerPack: "8.0kW 220VAC 60Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "MR800.4",
                accessoryType: "glass"
              }
            ],
            description:
              "Jekko를 세계적으로 유명하게 만들어준 SPX1040은 뛰어난 기능을 갖춘 소형 크레인으로 140cm. 이중 문 정도의 폭만 있다면, 얼마든지 통과할 수 있습니다. 거기에 더하여 그런 컴팩트함에서 나오는 것이라곤 믿기 힘든 4톤의 인양능력과 긴 붐은 이 크레인이 어떻게 젝코를 세계적으로 유명하게 만들어줬는지를 증명하고 있죠."
          },
          {
            modelName: "SPX650",
            dimensions: "4460 x 980 x 2020mm",
            bodyWeight: "5960kg",
            dryWeight: "5900kg",
            counterWeight: "",
            maxSafeLoad: "5000kg",
            maxLiftingHeight: "17.3m",
            maxLiftingLength: "14m",
            maxHeightTipLoadWinch: "2000kg",
            maxLengthTipLoadWinch: "600kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 82°",
            hoistingSpeed: "25 ~ 33m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "90m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "4510 x 4510mm",
            maxOutriggerLoad: "4800kg",
            trackDimensions: "980, (1380)mm",
            speed: "1.9km/h, (2.9km/h)",
            climbingAbility: "20°",
            groundPressure: "0.75kg/㎠",
            operatingMethod: "배터리",
            powerType: "",
            powerPack: "",
            powerSupply: "16kW 220VAC 60Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "4460 x 980 x 2020mm",
                bodyWeight: "5960 + 40kg\n(6000kg)",
                dryWeight: "5900kg",
                counterWeight: "",
                maxSafeLoad: "5000kg",
                maxLiftingHeight: "18.6m",
                maxLiftingLength: "14.95m",
                maxHeightTipLoadWinch: "2000kg",
                maxLengthTipLoadWinch: "450kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 82°",
                hoistingSpeed: "25 ~ 33m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "90m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "4510 x 4510mm",
                maxOutriggerLoad: "4800kg",
                trackDimensions: "980, (1380)mm",
                speed: "1.9km/h, (2.9km/h)",
                climbingAbility: "20°",
                groundPressure: "0.75kg/㎠",
                operatingMethod: "배터리",
                powerType: "",
                powerPack: "",
                powerSupply: "16kW 220VAC 60Hz",
                additionalOptions: "",
                accessoryName: "JIB 2000GX",
                accessoryType: "jib"
              },
              {
                dimensions: "4460 x 980 x 2020mm",
                bodyWeight: "5960 + 410kg\n(6370kg)",
                dryWeight: "5900kg",
                counterWeight: "",
                maxSafeLoad: "5000kg",
                maxLiftingHeight: "23.6m",
                maxLiftingLength: "20m",
                maxHeightTipLoadWinch: "800kg",
                maxLengthTipLoadWinch: "150kg",
                maxHeightTipLoadHook: "800kg",
                maxLengthTipLoadHook: "150kg",
                workingAngle: "0° ~ 82°",
                hoistingSpeed: "25 ~ 33m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "90m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "4510 x 4510mm",
                maxOutriggerLoad: "4800kg",
                trackDimensions: "980, (1380)mm",
                speed: "1.9km/h, (2.9km/h)",
                climbingAbility: "20°",
                groundPressure: "0.75kg/㎠",
                operatingMethod: "배터리",
                powerType: "",
                powerPack: "",
                powerSupply: "16kW 220VAC 60Hz",
                additionalOptions: "",
                accessoryName: "JIB 1200 3HX",
                accessoryType: "jib"
              },
              {
                dimensions: "4460 x 980 x 2020mm",
                bodyWeight: "5960 + 230kg\n(6190kg)",
                dryWeight: "5900kg",
                counterWeight: "",
                maxSafeLoad: "500kg",
                maxLiftingHeight: "17.2m",
                maxLiftingLength: "15.75m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "500kg",
                maxLengthTipLoadHook: "240kg",
                workingAngle: "0° ~ 82°\n(↑ 91° ↓ 92°)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4510 x 4510mm",
                maxOutriggerLoad: "4800kg",
                trackDimensions: "980, (1380)mm",
                speed: "1.9km/h, (2.9km/h)",
                climbingAbility: "20°",
                groundPressure: "0.75kg/㎠",
                operatingMethod: "배터리",
                powerType: "",
                powerPack: "",
                powerSupply: "16kW 220VAC 60Hz",
                additionalOptions: "",
                accessoryName: "JIB500GR",
                accessoryType: "grapple"
              }
            ],
            description:
              "진정한 멀티태스킹이란 무엇인지 보여주는 SPX650은 Jekko의 5톤 전기 거미크레인으로, 단순히 들어 올리는 것에 그치지 않고 건설, 산업 유지 보수, 유리 설치 등 다양한 현장에 적합합니다. 거기에 더하여 완전 전기식으로 작동하기 때문에 실내 및 도심의 현장에 배기가스 배출 없어 깨끗하고 조용한 작동을 제공합니다."
          },
          {
            modelName: "JF545",
            dimensions: "5450 x 1840 x 2750mm",
            bodyWeight: "17400kg",
            dryWeight: "17250kg",
            counterWeight: "3500kg",
            maxSafeLoad: "15500kg",
            maxLiftingHeight: "19m",
            maxLiftingLength: "16.15m",
            maxHeightTipLoadWinch: "3900kg",
            maxLengthTipLoadWinch: "2010kg",
            maxHeightTipLoadHook: "4450kg",
            maxLengthTipLoadHook: "2500kg",
            workingAngle: "-15° ~ 80°",
            hoistingSpeed: "36.5 ~ 47m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "60m",
            winchDiameter: "⌀12mm",
            outriggerExtensionDimensions: "6700 x 6700mm",
            maxOutriggerLoad: "11250kg",
            trackDimensions: "1840mm",
            speed: "2.5km/h",
            climbingAbility: "30°",
            groundPressure: "0.85kg/㎠",
            operatingMethod: "디젤(경유) 20L",
            powerType: "KUBOTA\nV3307-CR-TE4B\n(55,4kW 74HP)",
            powerPack: "",
            powerSupply: "13kW 400VAC 60Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "5450 x 1840 x 2750mm",
                bodyWeight: "17400 + 1260kg\n(18660kg)",
                dryWeight: "17250kg",
                counterWeight: "3500kg",
                maxSafeLoad: "15500kg",
                maxLiftingHeight: "30.6m",
                maxLiftingLength: "28.30m",
                maxHeightTipLoadWinch: "250kg",
                maxLengthTipLoadWinch: "305kg",
                maxHeightTipLoadHook: "500kg",
                maxLengthTipLoadHook: "600kg",
                workingAngle: "-15° ~ 80°",
                hoistingSpeed: "36.5 ~ 47m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "60m",
                winchDiameter: "⌀12mm",
                outriggerExtensionDimensions: "6700 x 6700mm",
                maxOutriggerLoad: "11250kg",
                trackDimensions: "1840mm",
                speed: "2.5km/h",
                climbingAbility: "30°",
                groundPressure: "0.85kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA\nV3307-CR-TE4B\n(55,4kW 74HP)",
                powerPack: "",
                powerSupply: "13kW 400VAC 60Hz",
                additionalOptions: "MWP-2PGR\n(바구니)",
                accessoryName: "JIB 3000.6HA",
                accessoryType: "jib"
              }
            ],
            description:
              "JF545는 굴절형 붐의 유연성과 강력함에 거미 크레인의 소형화와 다재다능함을 결합한 거미 크레인입니다. 최대 15.5톤의 인양 용량을 갖춘 이 고급 모델은 다재다능함, 정밀성, 그리고 소형 크기로 굴절형 크레인 시장에서 두각을 나타내고 있죠. JF545는 산업 유지 보수, 도심 지역 인양, 복잡한 공간 이동 등 어떤 작업이든, 너클 붐 설계를 통해서 쉽고 안정적으로 작업을 수행할 수 있도록 만들어져있습니다."
          }
        ]
      },
      {
        brandName: "Hoeflon",
        equipments: [
          {
            modelName: "C1",
            dimensions: "1750 x 700 x 1260mm",
            bodyWeight: "1060kg",
            dryWeight: "960kg",
            counterWeight: "290kg",
            maxSafeLoad: "550kg",
            maxLiftingHeight: "4.4m",
            maxLiftingLength: "3.3m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "490kg",
            maxLengthTipLoadHook: "190kg",
            workingAngle: "-5° ~ 75°",
            hoistingSpeed: "",
            slewingAngle: "136°",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "1478 x 1100mm",
            maxOutriggerLoad: "",
            trackDimensions: "700, (1000)mm",
            speed: "0.5km/h, (1.1km/h)",
            climbingAbility: "22°",
            groundPressure: "0.28kg/㎠",
            operatingMethod: "배터리",
            powerType: "",
            powerPack: "",
            powerSupply: "230V 60Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "1750 x 700 x 1260mm",
                bodyWeight: "1060kg",
                dryWeight: "960kg",
                counterWeight: "290kg",
                maxSafeLoad: "550kg",
                maxLiftingHeight: "5.7m",
                maxLiftingLength: "4.6m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "470kg",
                maxLengthTipLoadHook: "120kg",
                workingAngle: "-5° ~ 75°",
                hoistingSpeed: "",
                slewingAngle: "136°",
                slewingSpeed: "",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "1478 x 1100mm",
                maxOutriggerLoad: "",
                trackDimensions: "700, (1000)mm",
                speed: "0.5km/h, (1.1km/h)",
                climbingAbility: "22°",
                groundPressure: "0.28kg/㎠",
                operatingMethod: "배터리",
                powerType: "",
                powerPack: "",
                powerSupply: "230V 60Hz",
                additionalOptions: "",
                accessoryName: "FLY JIB",
                accessoryType: "jib"
              }
            ],
            description:
              "Hoeflon 고객들은 C1e의 확실한 장점으로 소형화와 기동성을 꼽았습니다. C1e는 굉장히 컴팩트해서 엘리베이터를 통해서도 운반이 가능할 정도로 간편하고 좁은 공간에서도 쉽게 조작할 수 있죠. 거기에 픽&캐리 기능을 지원하여 짐을 싣고 그대로 운반도 할 수 있습니다. 이 기능 덕분에 1층에서 창문을 설치하든 유지와 보수 작업에 투입되건 C1e는 완벽하게 작업을 처리할 수 있게 되죠. 또한 윈치 작업도 가능하도록 기본 옵션으로 25m 윈치도 장착이 되어있습니다."
          },
          {
            modelName: "C6",
            dimensions: "3140 x 750 x 1950mm",
            bodyWeight: "2650kg",
            dryWeight: "2630kg",
            counterWeight: "600kg",
            maxSafeLoad: "3000kg",
            maxLiftingHeight: "11.5m",
            maxLiftingLength: "9.2m",
            maxHeightTipLoadWinch: "900kg",
            maxLengthTipLoadWinch: "470kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 75°",
            hoistingSpeed: "20.8m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.5rpm",
            winchLength: "50m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4200 x 4400mm",
            maxOutriggerLoad: "2800kg",
            trackDimensions: "750, (1050)mm",
            speed: "1.1km/h, (2.2km/h)",
            climbingAbility: "20°",
            groundPressure: "0.79kg/㎠",
            operatingMethod: "리튬 배터리\n디젤(경유) 20L",
            powerType: "(C6) Yanmar 3-cylinder diesel\n(C6e) 80 V Lithium\n(9.5kW 12.7HP)",
            powerPack: "",
            powerSupply: "220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                dimensions: "3140 x 750 x 1950mm",
                bodyWeight: "2650 + 200kg\n(2850kg)",
                dryWeight: "2630kg",
                counterWeight: "600kg",
                maxSafeLoad: "3000kg",
                maxLiftingHeight: "16.4m",
                maxLiftingLength: "13.7m",
                maxHeightTipLoadWinch: "601kg",
                maxLengthTipLoadWinch: "210kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75°",
                hoistingSpeed: "20.8m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.5rpm",
                winchLength: "50m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4200 x 4400mm",
                maxOutriggerLoad: "2800kg",
                trackDimensions: "750, (1050)mm",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                groundPressure: "0.79kg/㎠",
                operatingMethod: "리튬 배터리\n디젤(경유) 20L",
                powerType: "(C6) Yanmar 3-cylinder diesel\n(C6e) 80 V Lithium\n(9.5kW 12.7HP)",
                powerPack: "",
                powerSupply: "220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "FLY JIB",
                accessoryType: "jib"
              },
              {
                dimensions: "3140 x 750 x 1950mm",
                bodyWeight: "2650 + 340kg\n(2990kg)",
                dryWeight: "2630kg",
                counterWeight: "",
                maxSafeLoad: "1250kg",
                maxLiftingHeight: "13.7m",
                maxLiftingLength: "11.4m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "680kg",
                maxLengthTipLoadHook: "120kg",
                workingAngle: "0° ~ 75°\n(↑103° ~ ↓100°)\n(← 45° 50°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.5rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4200 x 4400mm",
                maxOutriggerLoad: "2800kg",
                trackDimensions: "750, (1050)mm",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                groundPressure: "0.79kg/㎠",
                operatingMethod: "리튬 배터리\n디젤(경유) 20L",
                powerType: "(C6) Yanmar 3-cylinder diesel\n(C6e) 80 V Lithium\n(9.5kW 12.7HP)",
                powerPack: "",
                powerSupply: "220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "MC1200",
                accessoryType: "grapple"
              }
            ],
            description:
              "C6는 호플론(Hoeflon)의 소형 크레인 중에서도 가장 다재다능한 제품입니다. 인양 능력 3톤에 지브를 사용하면 최대 16m까지 뻗어나가며 회전식 아우트리거로 항상 안정적으로 유지되고 있죠. 무엇보다 가장 큰 장점은 차체 중량을 초과하는 하중도 인양할 수 있는 것으로 이 장점 덕분에 C6e는 유리 설치와 철골 작업의 정밀한 위치 조정에 적합하죠."
          },
          {
            modelName: "C10",
            dimensions: "4150 x 800 x 2070mm",
            bodyWeight: "4500kg",
            dryWeight: "4400kg",
            counterWeight: "1340kg",
            maxSafeLoad: "4000kg",
            maxLiftingHeight: "16.3m",
            maxLiftingLength: "13.5m",
            maxHeightTipLoadWinch: "2070kg",
            maxLengthTipLoadWinch: "430kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-5° ~ 83°",
            hoistingSpeed: "20.8m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "60m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4578 x 4578mm",
            maxOutriggerLoad: "4500kg",
            trackDimensions: "800, (1100)mm",
            speed: "1.1km/h, (2.2km/h)",
            climbingAbility: "20°",
            groundPressure: "0.72kg/㎠",
            operatingMethod: "리튬 배터리\n디젤(경유) 20L",
            powerType: "Yanmar 3 cylinder 7.3 kW\n80 V 163 Ah LiFePO₄\n(13kW 14.1HP)",
            powerPack: "",
            powerSupply: "220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                dimensions: "4150 x 800 x 2070mm",
                bodyWeight: "4500 + 200kg\n(4700kg)",
                dryWeight: "4400kg",
                counterWeight: "1340kg",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "22m",
                maxLiftingLength: "19.8m",
                maxHeightTipLoadWinch: "710kg",
                maxLengthTipLoadWinch: "198kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "-5° ~ 83°",
                hoistingSpeed: "20.8m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "60m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4578 x 4578mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "800, (1100)mm",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                groundPressure: "0.72kg/㎠",
                operatingMethod: "리튬 배터리\n디젤(경유) 20L",
                powerType: "Yanmar 3 cylinder 7.3 kW\n80 V 163 Ah LiFePO₄\n(13kW 14.1HP)",
                powerPack: "",
                powerSupply: "220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "FLY JIB",
                accessoryType: "jib"
              },
              {
                dimensions: "4150 x 800 x 2070mm",
                bodyWeight: "4500 + 340kg\n(4840kg)",
                dryWeight: "4400kg",
                counterWeight: "",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "18.5m",
                maxLiftingLength: "15.7m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "1200kg",
                maxLengthTipLoadHook: "100kg",
                workingAngle: "-5° ~ 83°\n(↑103° ~ ↓100°)\n(← 45° 50°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4578 x 4578mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "800, (1100)mm",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                groundPressure: "0.72kg/㎠",
                operatingMethod: "리튬 배터리\n디젤(경유) 20L",
                powerType: "Yanmar 3 cylinder 7.3 kW\n80 V 163 Ah LiFePO₄\n(13kW 14.1HP)",
                powerPack: "",
                powerSupply: "220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "MC1200",
                accessoryType: "grapple"
              }
            ],
            description:
              "강력한 파워, 정말이지 C10은 그 이름에 걸맞습니다. C10은 동급의 크레인 중에서 최고의 인양 능력을 자랑하며 특히나 수평 리프팅이 뛰어나죠. 거기에 더하여 인양 능력에 비해서 컴팩트한 사이즈 덕분에 좁은 공간도 쉽게 통과할 수 있어 옥상에서 철골을 설치하든 공장의 전체 생산 설비를 옮기든, C10e는 그 모든 작업을 완벽하게 처리할 수 있습니다."
          }
        ]
      },
      {
        brandName: "BEFARD",
        equipments: [
          {
            modelName: "XM800",
            dimensions: "2250 x 780 x 1460mm",
            bodyWeight: "1150kg",
            dryWeight: "1050kg",
            counterWeight: "102kg\n(5.8kg x 12)",
            maxSafeLoad: "800kg",
            maxLiftingHeight: "4.6m",
            maxLiftingLength: "3.5m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "455kg",
            maxLengthTipLoadHook: "280kg",
            workingAngle: "0° ~ 65°",
            hoistingSpeed: "20.8m/min",
            slewingAngle: "50°",
            slewingSpeed: "",
            winchLength: "50m",
            winchDiameter: "⌀6mm",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "780, (1100)mm",
            speed: "2.2km/h",
            climbingAbility: "25°",
            groundPressure: "",
            operatingMethod: "리튬 배터리",
            powerType: "48V 80Ah",
            powerPack: "",
            powerSupply: "220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            description:
              "픽&캐리에 특화된 BEFARD XM 800은 무선 조종 방식의 크레인으로 자국을 남기지 않는 트랙을 기본으로 탑재하여 실내외 어디에서나 작업할 수 있습니다. 배터리로 움직이기 때문에 친환경적인 것은 물론이고 픽&캐리가 아닌 보다 무거운 물건의 인양이 필요한 순간엔 트랙의 앞에 있는 확장 기능이 달린 아우트리거가 제 몫을 다 해줄 겁니다."
          }
          // {
          //   modelName: "XGR800",
          //   dimensions: "2800 x 930 x 1600mm",
          //   bodyWeight: "1600kg",
          //   dryWeight: "",
          //   counterWeight: "616kg\n(5kg x 40장)\n(16kg x 26장)",
          //   maxSafeLoad: "800kg",
          //   maxLiftingHeight: "5.5m",
          //   maxLiftingLength: "3.7m",
          //   maxHeightTipLoadWinch: "",
          //   maxLengthTipLoadWinch: "",
          //   maxHeightTipLoadHook: "350kg",
          //   maxLengthTipLoadHook: "420kg",
          //   workingAngle: "0° ~ 65°\n(↑95° ↓90°)\n(← 90° 90°→)",
          //   hoistingSpeed: "",
          //   slewingAngle: "",
          //   slewingSpeed: "",
          //   winchLength: "",
          //   winchDiameter: "",
          //   outriggerExtensionDimensions: "",
          //   maxOutriggerLoad: "",
          //   trackDimensions: "930mm",
          //   speed: "2.2km/h",
          //   climbingAbility: "25°",
          //   groundPressure: "",
          //   operatingMethod: "리튬 배터리",
          //   powerType: "230V 50Hz",
          //   powerPack: "",
          //   powerSupply: "",
          //   additionalOptions: "",
          //   isBrochure: false,
          //   isTechnicalData: false,
          //   description:
          //     "유리 조립 로봇 BEFARD XGR 및 XGRe는 무거운 유리와 창문을 조립하는 데 사용되는 캐터필러 방식의 매니퓰레이터입니다. 최대 5.55m 범위의 확장 장치를 장착할 수 있습니다. 기본으로 무선 조종 장치가 장착되어 있어 주행 및 기계 작동을 모두 지원합니다. 트랙 섀시를 사용하여 까다로운 건설 환경에서도 작업이 가능합니다."
          // }
        ]
      },
      {
        brandName: "UNIC",
        equipments: [
          {
            modelName: "URW295",
            dimensions: "2730 x 600 x 1430mm",
            bodyWeight: "2040kg",
            dryWeight: "1850kg",
            counterWeight: "",
            maxSafeLoad: "2900kg",
            maxLiftingHeight: "8.8m",
            maxLiftingLength: "8.65m",
            maxHeightTipLoadWinch: "650kg",
            maxLengthTipLoadWinch: "130kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "10 ~ 40m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.5rpm",
            winchLength: "54m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "3885 x 3935mm",
            maxOutriggerLoad: "",
            trackDimensions: "600mm",
            speed: "2.0km/h",
            climbingAbility: "20°",
            groundPressure: "0.48kg/㎠",
            operatingMethod: "가솔린(휘발유) 6L",
            powerType: "",
            powerPack: "3.7kW 220V 3상 4P",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            description:
              "URW295는 시중에서 가장 인기 있는 거미 크레인 중 하나입니다. 8.65m 붐은 최대 8.8m의 리프팅 높이를 제공하죠. 또한 UNIC URW-295 스파이더 크레인에는 Lift-Smart 첨단 안전 시스템이 탑재되어 있어, 안전 하중 표시기를 통해 크레인이 안전 작업 범위를 벗어나는 것을 방지합니다."
          },
          {
            modelName: "URW546",
            dimensions: "4870 x 1380 x 2035mm",
            bodyWeight: "4940kg",
            dryWeight: "4920kg",
            counterWeight: "",
            maxSafeLoad: "4000kg",
            maxLiftingHeight: "16m",
            maxLiftingLength: "15.52m",
            maxHeightTipLoadWinch: "860kg",
            maxLengthTipLoadWinch: "160kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "10 ~ 40m/min",
            slewingAngle: "360°",
            slewingSpeed: "2.5rpm",
            winchLength: "103m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "5900 x 5940mm",
            maxOutriggerLoad: "",
            trackDimensions: "1380mm",
            speed: "3.0km/h",
            climbingAbility: "23°",
            groundPressure: "0.47kg/㎠",
            operatingMethod: "디젤(경유) 40L",
            powerType: "Yanmar 3TNV80F\n(15.2kW 20.4HP)",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "RC 무선 조종기",
            isBrochure: true,
            isTechnicalData: false,
            description:
              "UNIC URW-546은 새로운 청정 배출 Tier 4 디젤 엔진을 탑재하여 까다로운 최신 배출가스 규정을 완벽하게 준수하고 있습니다. 또한 운전석에서의 조종뿐만 아니라 무선 리모컨으로도 정밀한 리프팅 및 적재 작업을 수행할 수 있으며 폭이 1.4m에 불과해서 내부 출입구 통과 및 작업 공간이 제한될 수 있는 좁은 공간에서의 작업에도 이상적입니다."
          },
          {
            modelName: "URW547",
            dimensions: "4955 x 1380 x 1980mm",
            bodyWeight: "5170kg",
            dryWeight: "5010kg",
            counterWeight: "",
            maxSafeLoad: "4000kg",
            maxLiftingHeight: "18.2m",
            maxLiftingLength: "17.83m",
            maxHeightTipLoadWinch: "300kg",
            maxLengthTipLoadWinch: "50kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "10 ~ 40m/min",
            slewingAngle: "360°",
            slewingSpeed: "2.5rpm",
            winchLength: "103m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "5900 x 5940mm",
            maxOutriggerLoad: "",
            trackDimensions: "1380mm",
            speed: "3.0km/h",
            climbingAbility: "23°",
            groundPressure: "0.48kg/㎠",
            operatingMethod: "디젤(경유) 40L",
            powerType: "Yanmar 3TNV80F\n(15.2kW 20.4HP)",
            powerPack: "입력 380V 출력 220V\n3상 4P 7.5kW",
            powerSupply: "",
            additionalOptions:
              "KM - 100 중량초과 자동 정지 장치\n디지털 인양중량 미터기\n무선 조종기\n- C4A, C2A -\nSLI(인양 무게 인디케이터) 무선 조종기\n- C4E,C2E -\nC4E + 파워팩\n-C4EM-\n단선용 후크\n-ALL-",
            isBrochure: true,
            isTechnicalData: false,
            description:
              "그 어떤 것보다 안전을 우선시한 URW-547은 무선 원격 제어 장치와 리프트-스마트 고급 안전 시스템, 리프팅 작업 전 섀시 안정화를 위한 아웃리거 인터록 등 보다 향상된 안전 기능이 기본으로 제공됩니다. 또한, 이 크레인에는 안정성 경고등과 안전 경고 알람을 포함한 전복 방지 기능이 탑재되어 있어 전복 위험을 방지하죠."
          },
          {
            modelName: "URW706",
            dimensions: "5610 x 1670 x 2185mm",
            bodyWeight: "7990kg",
            dryWeight: "7920kg",
            counterWeight: "",
            maxSafeLoad: "6000kg",
            maxLiftingHeight: "19.5m",
            maxLiftingLength: "18.6m",
            maxHeightTipLoadWinch: "1350kg",
            maxLengthTipLoadWinch: "200kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "10 ~ 40m/min",
            slewingAngle: "360°",
            slewingSpeed: "2.5rpm",
            winchLength: "111m",
            winchDiameter: "⌀10mm",
            outriggerExtensionDimensions: "6550 x 6460mm",
            maxOutriggerLoad: "",
            trackDimensions: "1670mm",
            speed: "3.0km/h",
            climbingAbility: "23°",
            groundPressure: "0.44kg/㎠",
            operatingMethod: "디젤(경유) 60L",
            powerType: "Kubota D7103-M-DI-E4B\n(18.5kW 24.81HP)",
            powerPack: "입력 380V 출력 220V\n3상 4P 7.5kW",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                dimensions: "5610 x 1670 x 2185mm",
                bodyWeight: "7990 + 205kg\n(8195kg)",
                dryWeight: "7920kg",
                counterWeight: "",
                maxSafeLoad: "6000kg",
                maxLiftingHeight: "22.615m",
                maxLiftingLength: "18.6m",
                maxHeightTipLoadWinch: "800kg",
                maxLengthTipLoadWinch: "300kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 80°",
                hoistingSpeed: "10 ~ 40m/min",
                slewingAngle: "360°",
                slewingSpeed: "2.5rpm",
                winchLength: "111m",
                winchDiameter: "⌀10mm",
                outriggerExtensionDimensions: "6550 x 6460mm",
                maxOutriggerLoad: "",
                trackDimensions: "1670mm",
                speed: "3.0km/h",
                climbingAbility: "23°",
                groundPressure: "0.44kg/㎠",
                operatingMethod: "디젤(경유) 60L",
                powerType: "Kubota D7103-M-DI-E4B\n(18.5kW 24.81HP)",
                powerPack: "입력 380V 출력 220V\n3상 4P 7.5kW",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "FLY JIB",
                accessoryType: "jib"
              },
              {
                dimensions: "5610 x 1670 x 2185mm",
                bodyWeight: "7990 + 480kg\n(8470kg)",
                dryWeight: "7920kg",
                counterWeight: "",
                maxSafeLoad: "6000kg",
                maxLiftingHeight: "25.9m",
                maxLiftingLength: "18.6m",
                maxHeightTipLoadWinch: "800kg",
                maxLengthTipLoadWinch: "150kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 80°",
                hoistingSpeed: "10 ~ 40m/min",
                slewingAngle: "360°",
                slewingSpeed: "2.5rpm",
                winchLength: "111m",
                winchDiameter: "⌀10mm",
                outriggerExtensionDimensions: "6550 x 6460mm",
                maxOutriggerLoad: "",
                trackDimensions: "1670mm",
                speed: "3.0km/h",
                climbingAbility: "23°",
                groundPressure: "0.44kg/㎠",
                operatingMethod: "디젤(경유) 60L",
                powerType: "Kubota D7103-M-DI-E4B\n(18.5kW 24.81HP)",
                powerPack: "입력 380V 출력 220V\n3상 4P 7.5kW",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "유압 지브",
                accessoryType: "jib"
              }
            ],
            description:
              "URW-706은 리프팅 유연성을 높이기 위해 플라이 지브를 장착하여 최대 22.615m까지 작업할 수 있고 추가로 무선 원격 제어 기능이 제공되어 작업자가 작업물이 있는 곳의 뒤나 멀리에서도 작업할 수 있어 가시성 향상 및 안전한 근접 작업, 정확한 적재가 가능합니다. 조종석과 무선 원격 제어장치에 달린 인양물의 무게에 대한 즉각적인 피드백을 해주는 인디케이터도 큰 장점이죠. 초고층 빌딩, 발전소, 옥상 작업, 쇼핑센터 작업에 적합한 작지만 강력한 URW-706은 다양한 작업 환경에서 작업 유연성과 강력한 성능을 완벽하게 결합한 거미크레인입니다."
          }
        ]
      },
      {
        brandName: "MAEDA",
        equipments: [
          {
            modelName: "MC305",
            dimensions: "4285 x 1280 x 1695mm",
            bodyWeight: "4080kg",
            dryWeight: "3900kg",
            counterWeight: "",
            maxSafeLoad: "2980kg",
            maxLiftingHeight: "12.5m",
            maxLiftingLength: "12.485m",
            maxHeightTipLoadWinch: "790kg",
            maxLengthTipLoadWinch: "260kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "54m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "73m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4890 x 4505mm",
            maxOutriggerLoad: "1010kg",
            trackDimensions: "1280mm",
            speed: "2.8km/h",
            climbingAbility: "23°",
            groundPressure: "0.37kg/㎠",
            operatingMethod: "디젤(경유) 40L",
            powerType: "Yanmar 3TNV76\n(15.2kW 20.4HP)",
            powerPack: "380V 4P 5.5kW",
            powerSupply: "",
            additionalOptions: "파워팩\n(CE-2)\n단선용 후크\n전자식 작업 인디케이터\n-ALL-",
            isBrochure: true,
            isTechnicalData: false,
            description:
              "MC305는 그 작은 크기에도 불구하고 매우 다재다능하며 강력한 성능을 자랑합니다. 폭은 128cm에 불과하지만, 인양 능력은 최대 2.98톤으로 강력하며 전자식 작업 인디케이터가 인양물에 대한 정보를 전달받아 실시간으로 전달해줘 작업자가 편안하게 작업할 수 있도록 도와주죠."
          },
          {
            modelName: "MC405",
            dimensions: "4980 x 1380 x 1980mm",
            bodyWeight: "5750kg",
            dryWeight: "5600kg",
            counterWeight: "",
            maxSafeLoad: "3830kg",
            maxLiftingHeight: "16.8m",
            maxLiftingLength: "16.475m",
            maxHeightTipLoadWinch: "1130kg",
            maxLengthTipLoadWinch: "210kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "54m/min",
            slewingAngle: "330°",
            slewingSpeed: "2.5rpm",
            winchLength: "92m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "5790 x 5520mm",
            maxOutriggerLoad: "1400kg",
            trackDimensions: "1380mm",
            speed: "3.3km/h",
            climbingAbility: "20°",
            groundPressure: "0.50kg/㎠",
            operatingMethod: "디젤(경유) 60L",
            powerType: "Yanmar 3TNV88\n(17.5kW 23.5HP)",
            powerPack: "380V 3P 7.5kW",
            powerSupply: "",
            additionalOptions: "파워팩\n(CE)\n단선용 후크\n전자식 작업 인디케이터\n-ALL-",
            isBrochure: true,
            isTechnicalData: false,
            description:
              "MC405는 인양 능력이 최대 3.83톤인 강력한 미니 크레인으로 전자식 인디케이터와 파워팩이 탑재되어 있어 인양물의 정보를 실시간으로 전달받아 손쉽게 작업을 할 수 있으며. 유사시에는 물건을 인양한 상태로 이동할 수 있도록 500kg의 픽&캐리 기능도 갖추고 있습니다."
          }
        ]
      }
    ]
  },
  {
    type: "crawler",
    brands: [
      {
        brandName: "MAEDA",
        equipments: [
          {
            modelName: "LC383",
            dimensions: "4020 x 1740 x 2495mm",
            bodyWeight: "4040kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "2930kg",
            maxLiftingHeight: "8.71m(정차)\n5.03m(주행)",
            maxLiftingLength: "8.38m (정차)\n4.7m (주행)",
            maxHeightTipLoadWinch: "1190kg(정차)\n1465kg(주행)",
            maxLengthTipLoadWinch: "200kg(정차)\n230kg(주행)",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "54m/min",
            slewingAngle: "330°",
            slewingSpeed: "1.0rpm",
            winchLength: "73m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "1740mm",
            speed: "2.9km/h, (4.6km/h)",
            climbingAbility: "20°",
            groundPressure: "0.44kg/㎠",
            operatingMethod: "디젤(경유) 42L",
            powerType: "Yanmar 3TNV88\n(21.5kW 28.8HP)",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            description:
              "LC383은 2.93톤의 크롤라 크레인으로 아우트리거가 필요 없는 매우 컴팩트한 트랙형 바닥과 스윙 반경이 트랙의 폭을 벗어나지 않는 거의 제로에 가까운 테일 스윙 덕분에 도심과 같이 공간이 제한된 지역에서 주로 사용하도록 개발되었습니다. 이 크레인의 주요 특징은 최대 1,465kg의 픽&캐리 용량이며 다른 특징으로는 9.3m의 리프팅 높이, 개방형이지만 덮개가 있는 운전실과 4,400kg 정도밖에 되지 않는 총중량 등이 있습니다."
          }
        ]
      },
      {
        brandName: "Kobelco",
        equipments: [
          {
            modelName: "CK120UR",
            dimensions: "5480 x 2490 x 2810mm",
            bodyWeight: "12470kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "4900kg",
            maxLiftingHeight: "14.77m(정차)\n9.51m(주행)",
            maxLiftingLength: "14.01m (정차)\n8.75m (주행)",
            maxHeightTipLoadWinch: "1400kg(정차)\n1400kg(주행)",
            maxLengthTipLoadWinch: "500kg(정차)\n550kg(주행)",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-1° ~ 80°",
            hoistingSpeed: "44m/min",
            slewingAngle: "360°",
            slewingSpeed: "2.5rpm",
            winchLength: "113m",
            winchDiameter: "⌀10mm",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "2490mm",
            speed: "1.9km/h, (3.2km/h)",
            climbingAbility: "20°",
            groundPressure: "0.43kg/㎠",
            operatingMethod: "디젤(경유) 95L",
            powerType: "Isuzu 4LE2XDPC\n(41kW 55HP)",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            description:
              "KOBELCO 4.9톤 크롤라 크레인 CK120UR은 단순히 높은 사양뿐만 아니라 실용적인 용량과 기능을 갖춘 뛰어난 크롤라 크레인을 제공하기 위해 개발되었습니다. 지하 도로 및 철도 인프라, 공공시설용 트렌치, 신축 건물 기초 공사, 고가 교량 또는 철도 선로 작업 등 작업 공간이 매우 제한적인 도시 현장에서 이 고성능 크롤라 크레인은 믿을 수 있는 작업 성능을 제공합니다."
          }
        ]
      },
      {
        brandName: "Jekko",
        equipments: [
          {
            modelName: "SPK60",
            dimensions: "3505 x 2320 x 2640mm",
            bodyWeight: "13760kg",
            dryWeight: "",
            counterWeight: "1560kg",
            maxSafeLoad: "6000kg",
            maxLiftingHeight: "17.7m(정차)\n10.6m(주행)",
            maxLiftingLength: "17.1m(정차)\n10m(주행)",
            maxHeightTipLoadWinch: "1320kg(정차)\n850kg(주행)",
            maxLengthTipLoadWinch: "250kg(정차)\n450kg(주행)",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 75° (정차)\n0° ~ 65° (주행)",
            hoistingSpeed: "30 ~ 55m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.2rpm",
            winchLength: "125m",
            winchDiameter: "⌀10mm",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "2320, (2920)mm",
            speed: "1.7km/h (3.1km/h)",
            climbingAbility: "10°",
            groundPressure: "0.9kg/㎠",
            operatingMethod: "디젤(경유) 105L",
            powerType: "Yanmar 4TNV98T\n(53.7kW 73HP)",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "3505 x 2320 x 2640mm",
                bodyWeight: "13760 + 674kg\n(14434kg)",
                dryWeight: "",
                counterWeight: "1560kg",
                maxSafeLoad: "6000kg",
                maxLiftingHeight: "25.2m(정차)",
                maxLiftingLength: "12m(정차)",
                maxHeightTipLoadWinch: "490kg(정차)",
                maxLengthTipLoadWinch: "110kg(정차)",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75°",
                hoistingSpeed: "30 ~ 55m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "125m",
                winchDiameter: "⌀10mm",
                outriggerExtensionDimensions: "",
                maxOutriggerLoad: "",
                trackDimensions: "2320, (2920)mm",
                speed: "1.7km/h (3.1km/h)",
                climbingAbility: "10°",
                groundPressure: "0.9kg/㎠",
                operatingMethod: "디젤(경유) 105L",
                powerType: "Yanmar 4TNV98T\n(53.7kW 73HP)",
                powerPack: "",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 1501.3HL",
                accessoryType: "jib"
              },
              {
                dimensions: "3505 x 2320 x 2640mm",
                bodyWeight: "13760 + 70kg\n(13830kg)",
                dryWeight: "",
                counterWeight: "1560kg",
                maxSafeLoad: "6000kg",
                maxLiftingHeight: "19.2m(정차)\n11.9m(주행)",
                maxLiftingLength: "18.6m(정차)\n11m(주행)",
                maxHeightTipLoadWinch: "1330kg(정차)\n600kg(정차)",
                maxLengthTipLoadWinch: "150kg(정차)\n250kg(주행)",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75° (정차)\n0° ~ 65° (주행)",
                hoistingSpeed: "30 ~ 55m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "125m",
                winchDiameter: "⌀10mm",
                outriggerExtensionDimensions: "",
                maxOutriggerLoad: "",
                trackDimensions: "2320, (2920)mm",
                speed: "1.7km/h (3.1km/h)",
                climbingAbility: "10°",
                groundPressure: "0.9kg/㎠",
                operatingMethod: "디젤(경유) 105L",
                powerType: "Yanmar 4TNV98T\n(53.7kW 73HP)",
                powerPack: "",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 3500GX",
                accessoryType: "jib"
              }
            ],
            description:
              "완벽한 밀폐형 운전실을 갖춘 크롤라 크레인입니다. 독립형 연장 트랙은 안정성을 높이고, 특히 제로 테일 스윙 방식으로 픽&캐리 모드에서도 항시 탁월한 성능을 발휘하여 좁은 공간에서의 작업에 이상적입니다. 운전실에 설치된 두 대의 비디오 카메라 모니터는 작업자가 자신이 작업하는 공간을 완벽하게 볼 수 있도록 해주며, 디지털로 되어있는 제어장치는 작업자의 입맛과 현장의 상황에 따라서 설정할 수 있습니다."
          }
        ]
      }
    ]
  },
  {
    type: "boom-lift",
    brands: [
      {
        brandName: "Cela",
        equipments: [
          {
            modelName: "DT15",
            dimensions: "4020 x 1740 x 2495mm",
            bodyWeight: "1550kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "200kg",
            maxLiftingHeight: "15m",
            maxLiftingLength: "7.5m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "200kg",
            maxLengthTipLoadHook: "200kg",
            workingAngle: "",
            hoistingSpeed: "",
            slewingAngle: "720°",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "4100 x 3400mm",
            maxOutriggerLoad: "",
            trackDimensions: "800mm",
            speed: "1.5km/h",
            climbingAbility: "",
            groundPressure: "",
            operatingMethod: "",
            powerType: "",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: false,
            isTechnicalData: true,
            description:
              "DT15에는 이중 바스켓 부착 장치가 있어 바스켓을 독립적으로 올리거나 내릴 수 있어 사용자의 특정 요구에 손쉽게 맞출 수 있습니다. 하지만 이것이 이 DT15의 전부는 아닙니다. DT15를 진정으로 차별화하는 것은 바로 이중 텔레스코픽 붐 기술입니다. 메인 붐과 지브 모두에 ​​이중 텔레스코픽 붐이 장착되어 거의 완벽한 원형 작업 영역을 만들어 장애물을 손쉽게 탐색하고 어떤 지점이든 탁월한 정밀도로 도달할 수 있습니다."
          },
          {
            modelName: "DT25",
            dimensions: "5480 x 2490 x 2810mm",
            bodyWeight: "2950kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "230kg",
            maxLiftingHeight: "25m",
            maxLiftingLength: "12m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "230kg",
            maxLengthTipLoadHook: "230kg",
            workingAngle: "",
            hoistingSpeed: "",
            slewingAngle: "720°",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "4815 x 3600mm",
            maxOutriggerLoad: "",
            trackDimensions: "1150mm",
            speed: "1.5km/h",
            climbingAbility: "",
            groundPressure: "",
            operatingMethod: "",
            powerType: "",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: false,
            isTechnicalData: true,
            description:
              "당사의 다른 유명한 DT 시리즈와 마찬가지로 신뢰할 수 있는 이중 텔레스코픽 붐(DT) 디자인을 채택하여 탁월한 도달 범위와 정밀성을 제공하며 다양한 바스켓 옵션을 갖추고 있습니다. 거기에 인증된 호이스트 후크와 윈치 부착 장치를 장착시켜 유사시에는 잠시 크레인처럼 변형시킬 수도 있죠. 또한 360도 바스켓 회전 기능을 통해 작업자에게 작업 공간에 대한 전례 없는 접근성을 제공합니다."
          },
          {
            modelName: "DT30",
            dimensions: "3505 x 2320 x 2640mm",
            bodyWeight: "5000kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "225kg",
            maxLiftingHeight: "30.20m",
            maxLiftingLength: "16m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "225kg",
            maxLengthTipLoadHook: "225kg",
            workingAngle: "",
            hoistingSpeed: "",
            slewingAngle: "360°",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "5880 x 4280mm",
            maxOutriggerLoad: "",
            trackDimensions: "1200mm",
            speed: "1.5km/h",
            climbingAbility: "",
            groundPressure: "",
            operatingMethod: "",
            powerType: "",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: false,
            isTechnicalData: true,
            description:
              "DT28의 성공을 기반으로 제작된 이 확장형 DT는 고객분들이 좋아하는 모든 놀라운 기능을 그대로 유지하면서도 두 번째 붐 끝에 특수 지브를 장착하여 고소 작업 시의 미세한 조작을 더욱 원활하게 했습니다. DT 30은 DT 고소 작업대의 모든 장점을 계승하면서도, 2m의 연장된 붐으로 더욱 넓은 작업 범위를 제공하죠. 이러한 특징으로 수목 재배, 지붕 공사, 도색 작업 등 다양한 분야의 전문가들에게 선호되는 제품입니다."
          }
        ]
      }
    ]
  }
];
