export const dictionaries = {
  modelName: "모델명",
  dimensions: "치수 (LxWxH)",
  outriggerExtensionDimensions: "아웃트리거 확장 치수",
  trackDimensions: "트랙 치수(확장)",
  boomLength: "붐 길이",
  maxLiftingHeight: "최대 인양높이",
  maxLiftingLength: "최대 인양길이",
  bodyWeight: "차체 무게",
  maxSafeLoad: "최대 안전하중",
  maxHeightTipLoad: "최대 높이 끝단 하중",
  maxLengthTipLoad: "최대 길이 끝단 하중",
  speed: "속력 1단, (2단)",
  climbingAbility: "등판 능력",
  workingAngle: "작업 각도",
  slewingAngle: "선회 각도",
  maxOutriggerLoad: "최대 아웃트리거 하중",
  groundPressure: "접지압",
  powerType: "디젤/배터리"
};

export const craneType = {
  jib: "보조붐",
  grapple: "집게",
  glass: "유리흡착기",
  crawler: "크롤러"
};

export const cranes = [
  {
    type: "spider",
    brands: [
      {
        brandName: "Jekko",
        equipments: [
          {
            modelName: "SPX312",
            dimensions: "2790 x 770 x 1600mm",
            outriggerExtensionDimensions: "3700 x 3700mm",
            trackDimensions: "770, (1065)mm",
            boomLength: "7.6m",
            maxLiftingHeight: "8.7m",
            maxLiftingLength: "7.3m",
            bodyWeight: "1915kg",
            maxSafeLoad: "1200kg",
            maxHeightTipLoad: "600kg",
            maxLengthTipLoad: "320kg",
            speed: "0.85km/h",
            climbingAbility: "20°",
            workingAngle: "0° ~ 75°",
            slewingAngle: "330°",
            maxOutriggerLoad: "1850kg",
            groundPressure: "0.55kg/㎠",
            powerType: "배터리",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "JIB",
                accessoryType: "jib",
                dimensions: "2790 x 770 x 1600mm",
                outriggerExtensionDimensions: "3700 x 3700mm",
                trackDimensions: "770, (1065)mm",
                boomLength: "9.8m",
                maxLiftingHeight: "10.9m",
                maxLiftingLength: "9.5m",
                bodyWeight: "1985kg",
                maxSafeLoad: "1200kg",
                maxHeightTipLoad: "300kg",
                maxLengthTipLoad: "100kg",
                speed: "0.85km/h",
                climbingAbility: "20°",
                workingAngle: "0° ~ 75°",
                slewingAngle: "330°",
                maxOutriggerLoad: "1850kg",
                groundPressure: "0.55kg/㎠",
                powerType: "배터리"
              }
            ]
          },
          {
            modelName: "SPX424",
            dimensions: "3165 x 775 x 1955mm",
            outriggerExtensionDimensions: "3730 x 3730mm",
            trackDimensions: "775, (1100)mm",
            boomLength: "8.5m",
            maxLiftingHeight: "10m",
            maxLiftingLength: "7.7m",
            bodyWeight: "2195kg",
            maxSafeLoad: "2400kg",
            maxHeightTipLoad: "1000kg",
            maxLengthTipLoad: "400kg",
            speed: "0.72km/h",
            climbingAbility: "20°",
            workingAngle: "0° ~ 75°",
            slewingAngle: "360°",
            maxOutriggerLoad: "2200kg",
            groundPressure: "0.55kg/㎠",
            powerType: "배터리",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "JIB",
                accessoryType: "jib",
                dimensions: "3165 x 775 x 1955mm",
                outriggerExtensionDimensions: "3730 x 3730mm",
                trackDimensions: "775, (1100)mm",
                boomLength: "13.85m",
                maxLiftingHeight: "15.2m",
                maxLiftingLength: "11.8m",
                bodyWeight: "2370kg",
                maxSafeLoad: "2400kg",
                maxHeightTipLoad: "300kg",
                maxLengthTipLoad: "110kg",
                speed: "0.72km/h",
                climbingAbility: "20°",
                workingAngle: "0° ~ 75°",
                slewingAngle: "360°",
                maxOutriggerLoad: "2200kg",
                groundPressure: "0.55kg/㎠",
                powerType: "배터리"
              },
              {
                accessoryName: "MR800.4",
                accessoryType: "glass",
                dimensions: "3165 x 775 x 1955mm",
                outriggerExtensionDimensions: "3730 x 3730mm",
                trackDimensions: "775, (1100)mm",
                boomLength: "9.8m",
                maxLiftingHeight: "11m",
                maxLiftingLength: "7m",
                bodyWeight: "2490kg",
                maxSafeLoad: "6패드(540kg) 10패드(800kg)",
                maxHeightTipLoad: "650kg",
                maxLengthTipLoad: "200kg",
                speed: "0.72km/h",
                climbingAbility: "20°",
                workingAngle: "0° ~ 75° (↑95° ↓45°) (← 90° 90°→)",
                slewingAngle: "360°",
                maxOutriggerLoad: "2200kg",
                groundPressure: "0.55kg/㎠",
                powerType: "배터리",
                isBrochure: true,
                isTechnicalData: true
              }
            ]
          },
          {
            modelName: "SPX527",
            dimensions: "4145 x 1100 x 1960mm",
            outriggerExtensionDimensions: "4160 x 4160mm",
            trackDimensions: "600, (1100)mm",
            boomLength: "12.1m",
            maxLiftingHeight: "12.1m",
            maxLiftingLength: "11m",
            bodyWeight: "3660kg",
            maxSafeLoad: "2700kg",
            maxHeightTipLoad: "1000kg",
            maxLengthTipLoad: "250kg",
            speed: "2.0km/h",
            climbingAbility: "25°",
            workingAngle: "-2° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "2700kg",
            groundPressure: "0.53kg/㎠",
            powerType: "디젤(경유) 20L",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "JIB 600.2H",
                accessoryType: "jib",
                dimensions: "4145 x 1100 x 1960mm",
                outriggerExtensionDimensions: "4160 x 4160mm",
                trackDimensions: "600, (1100)mm",
                boomLength: "16.3m",
                maxLiftingHeight: "18.3m",
                maxLiftingLength: "11.2m",
                bodyWeight: "3870kg",
                maxSafeLoad: "2700kg",
                maxHeightTipLoad: "600kg",
                maxLengthTipLoad: "190kg",
                speed: "2.0km/h",
                climbingAbility: "25°",
                workingAngle: "-2° ~ 80°",
                slewingAngle: "360°",
                maxOutriggerLoad: "2700kg",
                groundPressure: "0.53kg/㎠",
                powerType: "디젤(경유) 20L"
              },
              {
                accessoryName: "MR800.4",
                accessoryType: "glass",
                dimensions: "4145 x 1100 x 1960mm",
                outriggerExtensionDimensions: "4160 x 4160mm",
                trackDimensions: "600, (1100)mm",
                boomLength: "13.4m",
                maxLiftingHeight: "15.4m",
                maxLiftingLength: "9m",
                bodyWeight: "3955kg",
                maxSafeLoad: "6패드(540kg) 10패드(800kg)",
                maxHeightTipLoad: "600kg",
                maxLengthTipLoad: "150kg",
                speed: "2.0km/h",
                climbingAbility: "25°",
                workingAngle: "-2° ~ 80° (↑95° ↓45°) (← 90° 90°→)",
                slewingAngle: "360°",
                maxOutriggerLoad: "2700kg",
                groundPressure: "0.53kg/㎠",
                powerType: "디젤(경유) 20L"
              }
            ]
          },
          {
            modelName: "SPX328",
            dimensions: "2950 x 730 x 1610mm",
            outriggerExtensionDimensions: "3830 x 3865mm",
            trackDimensions: "730mm",
            boomLength: "8.5m",
            maxLiftingHeight: "10.4m",
            maxLiftingLength: "8.0m",
            bodyWeight: "2300kg",
            maxSafeLoad: "2800kg",
            maxHeightTipLoad: "850kg",
            maxLengthTipLoad: "250kg",
            speed: "1.2km/h, (2.6km/h)",
            climbingAbility: "12°",
            workingAngle: "-4.5° ~ 77°",
            slewingAngle: "360°",
            maxOutriggerLoad: "2100kg",
            groundPressure: "0.62kg/㎠",
            powerType: "배터리",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "Unknown",
                accessoryType: "jib",
                dimensions: "2950 x 730 x 1610mm",
                outriggerExtensionDimensions: "3830 x 3865mm",
                trackDimensions: "730mm",
                boomLength: "12.8m",
                maxLiftingHeight: "12.8m",
                maxLiftingLength: "10.4m",
                bodyWeight: "2450kg",
                maxSafeLoad: "2800kg",
                maxHeightTipLoad: "500kg",
                maxLengthTipLoad: "100kg",
                speed: "1.2km/h, (2.6km/h)",
                climbingAbility: "12°",
                workingAngle: "-4.5° ~ 77°",
                slewingAngle: "360°",
                maxOutriggerLoad: "2100kg",
                groundPressure: "0.62kg/㎠",
                powerType: "배터리"
              }
            ]
          },
          {
            modelName: "SPX532",
            dimensions: "3220 x 770 x 1950mm",
            outriggerExtensionDimensions: "4400 x 4400mm",
            trackDimensions: "770, (1050)mm",
            boomLength: "10.8m",
            maxLiftingHeight: "12.1m",
            maxLiftingLength: "9.5m",
            bodyWeight: "2560kg",
            maxSafeLoad: "3200kg",
            maxHeightTipLoad: "1450kg",
            maxLengthTipLoad: "470kg",
            speed: "2.7km/h",
            climbingAbility: "20°",
            workingAngle: "0° ~ 83°",
            slewingAngle: "360°",
            maxOutriggerLoad: "3000kg",
            groundPressure: "0.63kg/㎠",
            powerType: "배터리",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "Unknown",
                accessoryType: "jib",
                dimensions: "3220 x 770 x 1950mm",
                outriggerExtensionDimensions: "4400 x 4400mm",
                trackDimensions: "770, (1050)mm",
                boomLength: "15.6m",
                maxLiftingHeight: "17.3m",
                maxLiftingLength: "14.8m",
                bodyWeight: "2760kg",
                maxSafeLoad: "3200kg",
                maxHeightTipLoad: "400kg",
                maxLengthTipLoad: "100kg",
                speed: "2.7km/h",
                climbingAbility: "20°",
                workingAngle: "0° ~ 83°",
                slewingAngle: "360°",
                maxOutriggerLoad: "3000kg",
                groundPressure: "0.63kg/㎠",
                powerType: "배터리"
              },
              {
                accessoryName: "JIB500GR",
                accessoryType: "grapple",
                dimensions: "3220 x 770 x 1950mm",
                outriggerExtensionDimensions: "4400 x 4400mm",
                trackDimensions: "770, (1050)mm",
                boomLength: "11.9m",
                maxLiftingHeight: "13.6m",
                maxLiftingLength: "10m",
                bodyWeight: "2790kg",
                maxSafeLoad: "500kg",
                maxHeightTipLoad: "500kg",
                maxLengthTipLoad: "200kg",
                speed: "2.7km/h",
                climbingAbility: "20°",
                workingAngle: "0° ~ 83° (↑91° ~ ↓92°)",
                slewingAngle: "360°",
                maxOutriggerLoad: "3000kg",
                groundPressure: "0.63kg/㎠",
                powerType: "배터리"
              }
            ]
          },
          {
            modelName: "SPX1040",
            dimensions: "5390 x 1450 x 2040mm",
            outriggerExtensionDimensions: "4200 x 4200mm",
            trackDimensions: "1450mm",
            boomLength: "14.5m",
            maxLiftingHeight: "14.5m",
            maxLiftingLength: "13m",
            bodyWeight: "6400kg",
            maxSafeLoad: "4000kg",
            maxHeightTipLoad: "1800kg",
            maxLengthTipLoad: "550kg",
            speed: "2.0km/h",
            climbingAbility: "25°",
            workingAngle: "-4° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "4000kg",
            groundPressure: "0.59kg/㎠",
            powerType: "디젤(경유) 20L",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "JIB 600.2H",
                accessoryType: "jib",
                dimensions: "5390 x 1450 x 2040mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                trackDimensions: "1450mm",
                boomLength: "18.6m",
                maxLiftingHeight: "20.1m",
                maxLiftingLength: "13m",
                bodyWeight: "6710kg",
                maxSafeLoad: "4000kg",
                maxHeightTipLoad: "900kg",
                maxLengthTipLoad: "100kg",
                speed: "2.0km/h",
                climbingAbility: "25°",
                workingAngle: "-4° ~ 80°",
                slewingAngle: "360°",
                maxOutriggerLoad: "4000kg",
                groundPressure: "0.59kg/㎠",
                powerType: "디젤(경유) 20L",
                isBrochure: true,
                isTechnicalData: true
              },
              {
                accessoryName: "JIB 3500G",
                accessoryType: "jib",
                dimensions: "5390 x 1450 x 2040mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                trackDimensions: "1450mm",
                boomLength: "16.1m",
                maxLiftingHeight: "17.6m",
                maxLiftingLength: "14.6m",
                bodyWeight: "6470kg",
                maxSafeLoad: "4000kg",
                maxHeightTipLoad: "1600kg",
                maxLengthTipLoad: "300kg",
                speed: "2.0km/h",
                climbingAbility: "25°",
                workingAngle: "-4° ~ 80°",
                slewingAngle: "360°",
                maxOutriggerLoad: "4000kg",
                groundPressure: "0.59kg/㎠",
                powerType: "디젤(경유) 20L",
                isBrochure: true,
                isTechnicalData: true
              },
              {
                accessoryName: "JIB 100.1FL",
                accessoryType: "jib",
                dimensions: "5390 x 1450 x 2040mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                trackDimensions: "1450mm",
                boomLength: "22m",
                maxLiftingHeight: "23.5m",
                maxLiftingLength: "20.5m",
                bodyWeight: "6710kg",
                maxSafeLoad: "4000kg",
                maxHeightTipLoad: "800kg",
                maxLengthTipLoad: "300kg",
                speed: "2.0km/h",
                climbingAbility: "25°",
                workingAngle: "-4° ~ 80°",
                slewingAngle: "360°",
                maxOutriggerLoad: "4000kg",
                groundPressure: "0.59kg/㎠",
                powerType: "디젤(경유) 20L",
                isBrochure: true,
                isTechnicalData: true
              },
              {
                accessoryName: "MR800.4",
                accessoryType: "glass",
                dimensions: "5390 x 1450 x 2040mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                trackDimensions: "1450mm",
                boomLength: "16.3m",
                maxLiftingHeight: "17.8m",
                maxLiftingLength: "13m",
                bodyWeight: "6695kg",
                maxSafeLoad: "6패드(540kg) 10패드(800kg)",
                maxHeightTipLoad: "800kg",
                maxLengthTipLoad: "250kg",
                speed: "2.0km/h",
                climbingAbility: "25°",
                workingAngle: "-4° ~ 80° (↑95° ↓45°) (← 90° 90°→)",
                slewingAngle: "360°",
                maxOutriggerLoad: "4000kg",
                groundPressure: "0.59kg/㎠",
                powerType: "디젤(경유) 20L",
                isBrochure: true,
                isTechnicalData: true
              }
            ]
          },
          {
            modelName: "SPX650",
            dimensions: "4460 x 980 x 2020mm",
            outriggerExtensionDimensions: "4510 x 4510mm",
            trackDimensions: "980, (1380)mm",
            boomLength: "15.4m",
            maxLiftingHeight: "15.4m",
            maxLiftingLength: "14m",
            bodyWeight: "5960kg",
            maxSafeLoad: "5000kg",
            maxHeightTipLoad: "2000kg",
            maxLengthTipLoad: "600kg",
            speed: "1.9km/h, (2.9km/h)",
            climbingAbility: "20°",
            workingAngle: "0° ~ 82°",
            slewingAngle: "360°",
            maxOutriggerLoad: "4800kg",
            groundPressure: "0.75kg/㎠",
            powerType: "배터리",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "JIB 2000GX",
                accessoryType: "jib",
                dimensions: "4460 x 980 x 2020mm",
                outriggerExtensionDimensions: "4510 x 4510mm",
                trackDimensions: "980, (1380)mm",
                boomLength: "16.4m",
                maxLiftingHeight: "18.6m",
                maxLiftingLength: "14.95m",
                bodyWeight: "6000kg",
                maxSafeLoad: "5000kg",
                maxHeightTipLoad: "2000kg",
                maxLengthTipLoad: "450kg",
                speed: "1.9km/h, (2.9km/h)",
                climbingAbility: "20°",
                workingAngle: "0° ~ 82°",
                slewingAngle: "360°",
                maxOutriggerLoad: "4800kg",
                groundPressure: "0.75kg/㎠",
                powerType: "배터리",
                isBrochure: true,
                isTechnicalData: true
              },
              {
                accessoryName: "JIB 1200 3HX",
                accessoryType: "jib",
                dimensions: "4460 x 980 x 2020mm",
                outriggerExtensionDimensions: "4510 x 4510mm",
                trackDimensions: "980, (1380)mm",
                boomLength: "21.3m",
                maxLiftingHeight: "23.6m",
                maxLiftingLength: "20m",
                bodyWeight: "6370kg",
                maxSafeLoad: "5000kg",
                maxHeightTipLoad: "800kg",
                maxLengthTipLoad: "150kg",
                speed: "1.9km/h, (2.9km/h)",
                climbingAbility: "20°",
                workingAngle: "0° ~ 82°",
                slewingAngle: "360°",
                maxOutriggerLoad: "4800kg",
                groundPressure: "0.75kg/㎠",
                powerType: "배터리",
                isBrochure: true,
                isTechnicalData: true
              },
              {
                accessoryName: "JIB500GR",
                accessoryType: "grapple",
                dimensions: "3220 x 770 x 1950mm",
                outriggerExtensionDimensions: "4400 x 4400mm",
                trackDimensions: "770, (1050)mm",
                boomLength: "11.9m",
                maxLiftingHeight: "13.6m",
                maxLiftingLength: "10m",
                bodyWeight: "2790kg",
                maxSafeLoad: "500kg",
                maxHeightTipLoad: "500kg",
                maxLengthTipLoad: "200kg",
                speed: "2.7km/h",
                climbingAbility: "20°",
                workingAngle: "0° ~ 83° (↑91° ~ ↓92°)",
                slewingAngle: "360°",
                maxOutriggerLoad: "3000kg",
                groundPressure: "0.63kg/㎠",
                powerType: "배터리",
                isBrochure: true,
                isTechnicalData: true
              }
            ]
          },
          {
            modelName: "JF545",
            dimensions: "5450 x 1840 x 2750mm",
            outriggerExtensionDimensions: "6700 x 6700mm",
            trackDimensions: "1840mm",
            boomLength: "28.2m",
            maxLiftingHeight: "19.25m",
            maxLiftingLength: "16.25m",
            bodyWeight: "17250kg",
            maxSafeLoad: "15500kg",
            maxHeightTipLoad: "4450kg",
            maxLengthTipLoad: "2500kg",
            speed: "2.5km/h",
            climbingAbility: "30°",
            workingAngle: "-15° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "11250kg",
            groundPressure: "0.85kg/㎠",
            powerType: "디젤(경유) 20L",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "JIB 3000.6HA",
                accessoryType: "jib",
                dimensions: "5450 x 1840 x 2750mm",
                outriggerExtensionDimensions: "6700 x 6700mm",
                trackDimensions: "1840mm",
                boomLength: "28.2m",
                maxLiftingHeight: "31.75m",
                maxLiftingLength: "28.20m",
                bodyWeight: "18450kg",
                maxSafeLoad: "15500kg",
                maxHeightTipLoad: "500kg",
                maxLengthTipLoad: "600kg",
                speed: "2.5km/h",
                climbingAbility: "30°",
                workingAngle: "-15° ~ 80°",
                slewingAngle: "360°",
                maxOutriggerLoad: "11250kg",
                groundPressure: "0.85kg/㎠",
                powerType: "디젤(경유) 20L"
              },
              {
                accessoryName: "MWP-2PGR",
                accessoryType: "jib",
                dimensions: "5450 x 1840 x 2750mm",
                outriggerExtensionDimensions: "6700 x 6700mm",
                trackDimensions: "1840mm",
                boomLength: "28.2m",
                maxLiftingHeight: "29.8m",
                maxLiftingLength: "28.4m",
                bodyWeight: "18450kg",
                maxSafeLoad: "15500kg",
                maxHeightTipLoad: "200kg",
                maxLengthTipLoad: "200kg",
                speed: "2.5km/h",
                climbingAbility: "30°",
                workingAngle: "-15° ~ 80°",
                slewingAngle: "360°",
                maxOutriggerLoad: "11250kg",
                groundPressure: "0.85kg/㎠",
                powerType: "디젤(경유) 20L"
              }
            ]
          }
        ]
      },
      {
        brandName: "Hoeflon",
        equipments: [
          {
            modelName: "C1",
            dimensions: "1750 x 700 x 1260mm",
            outriggerExtensionDimensions: "",
            trackDimensions: "700, (1000)mm",
            boomLength: "4.4m",
            maxLiftingHeight: "5.7m",
            maxLiftingLength: "3.3m",
            bodyWeight: "1060kg",
            maxSafeLoad: "550kg",
            maxHeightTipLoad: "230kg",
            maxLengthTipLoad: "130kg",
            speed: "0.5km/h, (1.1km/h)",
            climbingAbility: "22°",
            workingAngle: "-5° ~ 75°",
            slewingAngle: "136°",
            maxOutriggerLoad: "",
            groundPressure: "0.28kg/㎠",
            powerType: "배터리",
            isBrochure: true,
            isTechnicalData: true
          },
          {
            modelName: "C6",
            dimensions: "3140 x 750 x 1950mm",
            outriggerExtensionDimensions: "4200 x 4400mm",
            trackDimensions: "750, (1050)mm",
            boomLength: "8.5m",
            maxLiftingHeight: "11.5m",
            maxLiftingLength: "9.2m",
            bodyWeight: "2650kg",
            maxSafeLoad: "3000kg",
            maxHeightTipLoad: "820kg",
            maxLengthTipLoad: "420kg",
            speed: "1.1km/h, (2.2km/h)",
            climbingAbility: "20°",
            workingAngle: "0° ~ 75°",
            slewingAngle: "360°",
            maxOutriggerLoad: "2800kg",
            groundPressure: "0.79kg/㎠",
            powerType: "배터리/디젤(경유) 20L",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                accessoryName: "JIB",
                accessoryType: "jib",
                dimensions: "3140 x 750 x 1950mm",
                outriggerExtensionDimensions: "4200 x 4400mm",
                trackDimensions: "750, (1050)mm",
                boomLength: "14.05m",
                maxLiftingHeight: "15.8m",
                maxLiftingLength: "13.7m",
                bodyWeight: "2850kg",
                maxSafeLoad: "3000kg",
                maxHeightTipLoad: "601kg",
                maxLengthTipLoad: "211kg",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                workingAngle: "0° ~ 75°",
                slewingAngle: "360°",
                maxOutriggerLoad: "2800kg",
                groundPressure: "0.79kg/㎠",
                powerType: "배터리/디젤(경유) 20L",
                isBrochure: true,
                isTechnicalData: false
              },
              {
                accessoryName: "MC1200",
                accessoryType: "grapple",
                dimensions: "3140 x 750 x 1950mm",
                outriggerExtensionDimensions: "4200 x 4400mm",
                trackDimensions: "750, (1050)mm",
                boomLength: "13.7m",
                maxLiftingHeight: "13.7m",
                maxLiftingLength: "11.5m",
                bodyWeight: "2990kg",
                maxSafeLoad: "1250kg",
                maxHeightTipLoad: "680kg",
                maxLengthTipLoad: "160kg",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                workingAngle: "0° ~ 75° (↑103° ~ ↓100°) (← 45° 50°→)",
                slewingAngle: "360°",
                maxOutriggerLoad: "2800kg",
                groundPressure: "0.79kg/㎠",
                powerType: "배터리/디젤(경유) 20L",
                isBrochure: true,
                isTechnicalData: false
              }
            ]
          },

          {
            modelName: "C10",
            dimensions: "4150 x 800 x 2070mm",
            outriggerExtensionDimensions: "4580 x 4580mm",
            trackDimensions: "800, (1100)mm",
            boomLength: "16m",
            maxLiftingHeight: "16.3m",
            maxLiftingLength: "13.5m",
            bodyWeight: "4400kg",
            maxSafeLoad: "4000kg",
            maxHeightTipLoad: "1830kg",
            maxLengthTipLoad: "370kg",
            speed: "1.1km/h, (2.2km/h)",
            climbingAbility: "20°",
            workingAngle: "-5° ~ 83°",
            slewingAngle: "360°",
            maxOutriggerLoad: "4500kg",
            groundPressure: "0.72kg/㎠",
            powerType: "배터리/디젤(경유) 20L",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                accessoryName: "JIB",
                accessoryType: "jib",
                dimensions: "4150 x 800 x 2070mm",
                outriggerExtensionDimensions: "4580 x 4580mm",
                trackDimensions: "800, (1100)mm",
                boomLength: "19.6m",
                maxLiftingHeight: "21.3m",
                maxLiftingLength: "19m",
                bodyWeight: "4700kg",
                maxSafeLoad: "4000kg",
                maxHeightTipLoad: "748kg",
                maxLengthTipLoad: "209kg",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                workingAngle: "-5° ~ 83°",
                slewingAngle: "360°",
                maxOutriggerLoad: "4500kg",
                groundPressure: "0.72kg/㎠",
                powerType: "배터리/디젤(경유) 20L"
              },
              {
                accessoryName: "MC1200",
                accessoryType: "grapple",
                dimensions: "4150 x 800 x 2070mm",
                outriggerExtensionDimensions: "4580 x 4580mm",
                trackDimensions: "800, (1100)mm",
                boomLength: "18.5m",
                maxLiftingHeight: "18.5m",
                maxLiftingLength: "15.9m",
                bodyWeight: "4740kg",
                maxSafeLoad: "1200kg",
                maxHeightTipLoad: "1200kg",
                maxLengthTipLoad: "100kg",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                workingAngle: "-5° ~ 83° (↑103° ~ ↓100°) (← 45° 50°→)",
                slewingAngle: "360°",
                maxOutriggerLoad: "4500kg",
                groundPressure: "0.72kg/㎠",
                powerType: "배터리/디젤(경유) 20L"
              }
            ]
          }
        ]
      },
      {
        brandName: "BEFARD",
        equipments: [
          {
            modelName: "XM800",
            dimensions: "2250 x 780 x 1460mm",
            outriggerExtensionDimensions: "",
            trackDimensions: "780, (1100)mm",
            boomLength: "4.6m",
            maxLiftingHeight: "4.6m",
            maxLiftingLength: "3.5m",
            bodyWeight: "1150kg",
            maxSafeLoad: "800kg",
            maxHeightTipLoad: "455kg",
            maxLengthTipLoad: "280kg",
            speed: "2.2km/h",
            climbingAbility: "25°",
            workingAngle: "",
            slewingAngle: "50°",
            maxOutriggerLoad: "",
            groundPressure: "",
            powerType: "배터리",
            isBrochure: true,
            isTechnicalData: false
          }
        ]
      },
      {
        brandName: "UNIC",
        equipments: [
          {
            modelName: "URW295C",
            dimensions: "2730 x 600 x 1430mm",
            outriggerExtensionDimensions: "3885 x 3935mm",
            trackDimensions: "600mm",
            boomLength: "8.65m",
            maxLiftingHeight: "8.8m",
            maxLiftingLength: "8.65m",
            bodyWeight: "2040kg",
            maxSafeLoad: "2900kg",
            maxHeightTipLoad: "550kg",
            maxLengthTipLoad: "130kg",
            speed: "2.0km/h",
            climbingAbility: "20°",
            workingAngle: "0° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "",
            groundPressure: "0.48kg/㎠",
            powerType: "가솔린(휘발유) 6L",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "URW546",
            dimensions: "4870 x 1380 x 2035mm",
            outriggerExtensionDimensions: "5900 x 5940mm",
            trackDimensions: "1380mm",
            boomLength: "15.7m",
            maxLiftingHeight: "16m",
            maxLiftingLength: "15.52m",
            bodyWeight: "4920kg",
            maxSafeLoad: "4000kg",
            maxHeightTipLoad: "860kg",
            maxLengthTipLoad: "160kg",
            speed: "3.0km/h",
            climbingAbility: "23°",
            workingAngle: "0° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "",
            groundPressure: "0.47kg/㎠",
            powerType: "디젤(경유) 40L",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "URW547C",
            dimensions: "4955 x 1380 x 1980mm",
            outriggerExtensionDimensions: "5900 x 5940mm",
            trackDimensions: "1380mm",
            boomLength: "18.2m",
            maxLiftingHeight: "18.2m",
            maxLiftingLength: "18.02m",
            bodyWeight: "5020kg",
            maxSafeLoad: "4000kg",
            maxHeightTipLoad: "300kg",
            maxLengthTipLoad: "170kg",
            speed: "3.0km/h",
            climbingAbility: "23°",
            workingAngle: "0° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "",
            groundPressure: "0.48kg/㎠",
            powerType: "디젤(경유) 40L",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "URW706C",
            dimensions: "5610 x 1670 x 2185mm",
            outriggerExtensionDimensions: "6550 x 6460mm",
            trackDimensions: "1670mm",
            boomLength: "",
            maxLiftingHeight: "19.2m",
            maxLiftingLength: "19.5m",
            bodyWeight: "7920kg",
            maxSafeLoad: "6000kg",
            maxHeightTipLoad: "1350kg",
            maxLengthTipLoad: "200kg",
            speed: "3.0km/h",
            climbingAbility: "23°",
            workingAngle: "0° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "",
            groundPressure: "0.44kg/㎠",
            powerType: "디젤(경유) 60L",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                accessoryName: "유압 지브",
                accessoryType: "jib",
                dimensions: "5610 x 1670 x 2185mm",
                outriggerExtensionDimensions: "6550 x 6460mm",
                trackDimensions: "1670mm",
                boomLength: "",
                maxLiftingHeight: "25.2m",
                maxLiftingLength: "25.9m",
                bodyWeight: "8400kg",
                maxSafeLoad: "6000kg",
                maxHeightTipLoad: "800kg",
                maxLengthTipLoad: "150kg",
                speed: "3.0km/h",
                climbingAbility: "23°",
                workingAngle: "0° ~ 80°",
                slewingAngle: "360°",
                maxOutriggerLoad: "",
                groundPressure: "0.44kg/㎠",
                powerType: "디젤(경유) 60L",
                isBrochure: true,
                isTechnicalData: false
              },
              {
                accessoryName: "플라잉 지브",
                accessoryType: "jib",
                dimensions: "5610 x 1670 x 2185mm",
                outriggerExtensionDimensions: "6550 x 6460mm",
                trackDimensions: "1670mm",
                boomLength: "",
                maxLiftingHeight: "22.315m",
                maxLiftingLength: "22.7m",
                bodyWeight: "8400kg",
                maxSafeLoad: "6000kg",
                maxHeightTipLoad: "800kg",
                maxLengthTipLoad: "300kg",
                speed: "3.0km/h",
                climbingAbility: "23°",
                workingAngle: "0° ~ 80°",
                slewingAngle: "360°",
                maxOutriggerLoad: "",
                groundPressure: "0.44kg/㎠",
                powerType: "디젤(경유) 60L",
                isBrochure: true,
                isTechnicalData: false
              }
            ]
          }
        ]
      },
      {
        brandName: "MAEDA",
        equipments: [
          {
            modelName: "MC305",
            dimensions: "4285 x 1280 x 1695mm",
            outriggerExtensionDimensions: "4890 x 4505mm",
            trackDimensions: "1280mm",
            boomLength: "12.4m",
            maxLiftingHeight: "12.5m",
            maxLiftingLength: "12.485m",
            bodyWeight: "3900kg",
            maxSafeLoad: "2980kg",
            maxHeightTipLoad: "790kg",
            maxLengthTipLoad: "260kg",
            speed: "2.8km/h",
            climbingAbility: "23°",
            workingAngle: "0° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "1010kg",
            groundPressure: "0.37kg/㎠",
            powerType: "디젤(경유) 40L",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "MC405",
            dimensions: "4980 x 1380 x 1980mm",
            outriggerExtensionDimensions: "5790 x 5520mm",
            trackDimensions: "1380mm",
            boomLength: "16.4m",
            maxLiftingHeight: "16.8m",
            maxLiftingLength: "16.475m",
            bodyWeight: "5600kg",
            maxSafeLoad: "3830kg",
            maxHeightTipLoad: "1130kg",
            maxLengthTipLoad: "210kg",
            speed: "3.3km/h",
            climbingAbility: "20°",
            workingAngle: "0° ~ 80°",
            slewingAngle: "330°",
            maxOutriggerLoad: "1400kg",
            groundPressure: "0.50kg/㎠",
            powerType: "디젤(경유) 60L",
            isBrochure: true,
            isTechnicalData: false
          }
        ]
      }
    ]
  },
  {
    type: "crawler",
    brands: [
      {
        brandName: "MAEDA",
        equipments: [
          {
            modelName: "LC383",
            dimensions: "4020 x 1740 x 2495mm",
            outriggerExtensionDimensions: "",
            trackDimensions: "1740mm",
            boomLength: "8.71m",
            maxLiftingHeight: "9.3m",
            maxLiftingLength: "8.71m",
            bodyWeight: "4040kg",
            maxSafeLoad: "2930kg",
            maxHeightTipLoad: "1190kg",
            maxLengthTipLoad: "200kg",
            speed: "2.9km/h, (4.6km/h)",
            climbingAbility: "20°",
            workingAngle: "0° ~ 80°",
            slewingAngle: "330°",
            maxOutriggerLoad: "",
            groundPressure: "0.44kg/㎠",
            powerType: "디젤(경유) 42L",
            isBrochure: true,
            isTechnicalData: false
          }
        ]
      },
      {
        brandName: "Kobelco",
        equipments: [
          {
            modelName: "CK120UR",
            dimensions: "5480 x 2490 x 2810mm",
            outriggerExtensionDimensions: "",
            trackDimensions: "2490mm",
            boomLength: "14,77m",
            maxLiftingHeight: "17m",
            maxLiftingLength: "14m",
            bodyWeight: "12470kg",
            maxSafeLoad: "4900lg",
            maxHeightTipLoad: "500kg",
            maxLengthTipLoad: "200kg",
            speed: "1.9km/h, (3.2km/h)",
            climbingAbility: "20°",
            workingAngle: "-1° ~ 80°",
            slewingAngle: "360°",
            maxOutriggerLoad: "",
            groundPressure: "0.43kg/㎠",
            powerType: "디젤(경유) 95L",
            isBrochure: true,
            isTechnicalData: false
          }
        ]
      },
      {
        brandName: "Jekko",
        equipments: [
          {
            modelName: "SPK60",
            dimensions: "3505 x 2320 x 2640mm",
            outriggerExtensionDimensions: "",
            trackDimensions: "2320, (2920)mm",
            boomLength: "17.7m",
            maxLiftingHeight: "19.2m",
            maxLiftingLength: "17m",
            bodyWeight: "13760kg",
            maxSafeLoad: "6000kg",
            maxHeightTipLoad: "1320kg",
            maxLengthTipLoad: "250kg",
            speed: "3.1km/h",
            climbingAbility: "10°",
            workingAngle: "0° ~ 75°",
            slewingAngle: "360°",
            maxOutriggerLoad: "",
            groundPressure: "0.90kg/㎠",
            powerType: "디젤(경유) 105L",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                accessoryName: "JIB 1501.3HL",
                accessoryType: "crawler",
                dimensions: "3505 x 2320 x 2640mm",
                outriggerExtensionDimensions: "3506 x 2320 x 2640mm",
                trackDimensions: "2320, (2920)mm",
                boomLength: "25.2m",
                maxLiftingHeight: "26.7m",
                maxLiftingLength: "12m",
                bodyWeight: "14434kg",
                maxSafeLoad: "6000kg",
                maxHeightTipLoad: "490kg",
                maxLengthTipLoad: "110kg",
                speed: "3.1km/h",
                climbingAbility: "10°",
                workingAngle: "0° ~ 75°",
                slewingAngle: "360°",
                maxOutriggerLoad: "361°",
                groundPressure: "0.90kg/㎠",
                powerType: "디젤(경유) 105L",
                isBrochure: true,
                isTechnicalData: true
              },
              {
                accessoryName: "JIB 3500GX",
                accessoryType: "crawler",
                dimensions: "3505 x 2320 x 2640mm",
                outriggerExtensionDimensions: "",
                trackDimensions: "2320, (2920)mm",
                boomLength: "19.2m",
                maxLiftingHeight: "20.7m",
                maxLiftingLength: "18.5m",
                bodyWeight: "13830kg",
                maxSafeLoad: "6000kg",
                maxHeightTipLoad: "1320kg",
                maxLengthTipLoad: "250kg",
                speed: "3.1km/h",
                climbingAbility: "10°",
                workingAngle: "0° ~ 75°",
                slewingAngle: "360°",
                maxOutriggerLoad: "",
                groundPressure: "0.90kg/㎠",
                powerType: "디젤(경유) 105L",
                isBrochure: true,
                isTechnicalData: true
              }
            ]
          }
        ]
      }
    ]
  },
  {
    type: "boom-lift",
    brands: [
      {
        brandName: "Cela",
        equipments: [
          {
            modelName: "DT15",
            dimensions: "4020 x 1740 x 2495mm",
            outriggerExtensionDimensions: "4100 x 3400mm",
            trackDimensions: "800mm",
            boomLength: "15m",
            maxLiftingHeight: "15m",
            maxLiftingLength: "7.5m",
            bodyWeight: "1550kg",
            maxSafeLoad: "200kg",
            maxHeightTipLoad: "200kg",
            maxLengthTipLoad: "200kg",
            speed: "1.5km/h",
            climbingAbility: "",
            workingAngle: "",
            slewingAngle: "720°",
            maxOutriggerLoad: "",
            groundPressure: "",
            powerType: "",
            isBrochure: false,
            isTechnicalData: true
          },
          {
            modelName: "DT25",
            dimensions: "5480 x 2490 x 2810mm",
            outriggerExtensionDimensions: "4815 x 3600mm",
            trackDimensions: "1150mm",
            boomLength: "25m",
            maxLiftingHeight: "25m",
            maxLiftingLength: "12m",
            bodyWeight: "2950kg",
            maxSafeLoad: "230kg",
            maxHeightTipLoad: "230kg",
            maxLengthTipLoad: "230kg",
            speed: "1.5km/h",
            climbingAbility: "",
            workingAngle: "",
            slewingAngle: "720°",
            maxOutriggerLoad: "",
            groundPressure: "",
            powerType: "",
            isBrochure: false,
            isTechnicalData: true
          },
          {
            modelName: "DT30",
            dimensions: "3505 x 2320 x 2640mm",
            outriggerExtensionDimensions: "5880 x 4280mm",
            trackDimensions: "1200mm",
            boomLength: "30.20m",
            maxLiftingHeight: "30.20m",
            maxLiftingLength: "16m",
            bodyWeight: "5000kg",
            maxSafeLoad: "225kg",
            maxHeightTipLoad: "225kg",
            maxLengthTipLoad: "225kg",
            speed: "1.5km/h",
            climbingAbility: "",
            workingAngle: "",
            slewingAngle: "360°",
            maxOutriggerLoad: "",
            groundPressure: "",
            powerType: "",
            isBrochure: false,
            isTechnicalData: true
          }
        ]
      }
    ]
  }
];
