export const dictionaries = {
  modelName: "모델명",
  dimensions: "치수 (LxWxH)",
  bodyWeight: "차체 무게",
  dryWeight: "건조 무게 (드라이 웨이트)",
  counterWeight: "카운터 웨이트",
  maxSafeLoad: "최대 안전하중",
  maxLiftingHeight: "최대 인양높이",
  maxLiftingLength: "최대 인양길이",
  maxHeightTipLoadWinch: "최대 높이 끝단 하중 (윈치)",
  maxLengthTipLoadWinch: "최대 길이 끝단 하중 (윈치)",
  maxHeightTipLoadHook: "최대 높이 끝단 하중 (후크)(집게)(패드)",
  maxLengthTipLoadHook: "최대 길이 끝단 하중 (후크)(집게)(패드)",
  workingAngle: "작업 각도",
  hoistingSpeed: "권상 속도",
  slewingAngle: "선회 각도",
  slewingSpeed: "선회 속도",
  winchLength: "윈치 길이",
  winchDiameter: "윈치 두께 (⌀ = 직경)",
  outriggerExtensionDimensions: "아웃트리거 확장 치수",
  maxOutriggerLoad: "최대아웃트리거하중",
  trackDimensions: "트랙 치수(확장)",
  speed: "속력 1단, (2단)",
  climbingAbility: "등판 능력",
  groundPressure: "접지압",
  operatingMethod: "작동방식",
  powerType: "엔진/배터리 (HP : 마력)",
  powerPack: "파워팩",
  powerSupply: "사용 전원",
  additionalOptions: "추가 옵션"
};

export const craneType = {
  jib: "보조붐",
  grapple: "집게",
  glass: "유리흡착기",
  crawler: "크롤러"
} as const;

export type AccessoryType = keyof typeof craneType;

export type Accessory = {
  accessoryName: string; // 악세서리명
  accessoryType: AccessoryType; // 악세서리 타입
  dimensions: string; // 치수 (LxWxH)
  bodyWeight: string; // 차체 무게
  dryWeight: string; // 건조 무게 (드라이 웨이트)
  counterWeight: string; // 카운터 웨이트
  maxSafeLoad: string; // 최대 안전하중
  maxLiftingHeight: string; // 최대 인양높이
  maxLiftingLength: string; // 최대 인양길이
  maxHeightTipLoadWinch: string; // 최대 높이 끝단 하중 (윈치)
  maxLengthTipLoadWinch: string; // 최대 길이 끝단 하중 (윈치)
  maxHeightTipLoadHook: string; // 최대 높이 끝단 하중 (후크)(집게)(패드)
  maxLengthTipLoadHook: string; // 최대 길이 끝단 하중 (후크)(집게)(패드)
  workingAngle: string; // 작업 각도
  hoistingSpeed: string; // 권상 속도
  slewingAngle: string; // 선회 각도
  slewingSpeed: string; // 선회 속도
  winchLength: string; // 윈치 길이
  winchDiameter: string; // 윈치 두께 (⌀ = 직경)
  outriggerExtensionDimensions: string; // 아웃트리거 확장 치수
  maxOutriggerLoad: string; // 최대아웃트리거하중
  trackDimensions: string; // 트랙 치수(확장)
  speed: string; // 속력 1단, (2단)
  climbingAbility: string; // 등판 능력
  groundPressure: string; // 접지압
  operatingMethod: string; // 작동방식
  powerType: string; // 엔진/배터리 (HP : 마력)
  powerPack: string; // 파워팩
  powerSupply: string; // 사용 전원
  additionalOptions: string; // 추가 옵션
};

export type Equipment = {
  modelName: string; // 모델명
  dimensions: string; // 치수 (LxWxH)
  bodyWeight: string; // 차체 무게
  dryWeight: string; // 건조 무게 (드라이 웨이트)
  counterWeight: string; // 카운터 웨이트
  maxSafeLoad: string; // 최대 안전하중
  maxLiftingHeight: string; // 최대 인양높이
  maxLiftingLength: string; // 최대 인양길이
  maxHeightTipLoadWinch: string; // 최대 높이 끝단 하중 (윈치)
  maxLengthTipLoadWinch: string; // 최대 길이 끝단 하중 (윈치)
  maxHeightTipLoadHook: string; // 최대 높이 끝단 하중 (후크)(집게)(패드)
  maxLengthTipLoadHook: string; // 최대 길이 끝단 하중 (후크)(집게)(패드)
  workingAngle: string; // 작업 각도
  hoistingSpeed: string; // 권상 속도
  slewingAngle: string; // 선회 각도
  slewingSpeed: string; // 선회 속도
  winchLength: string; // 윈치 길이
  winchDiameter: string; // 윈치 두께 (⌀ = 직경)
  outriggerExtensionDimensions: string; // 아웃트리거 확장 치수
  maxOutriggerLoad: string; // 최대아웃트리거하중
  trackDimensions: string; // 트랙 치수(확장)
  speed: string; // 속력 1단, (2단)
  climbingAbility: string; // 등판 능력
  groundPressure: string; // 접지압
  operatingMethod: string; // 작동방식
  powerType: string; // 엔진/배터리 (HP : 마력)
  powerPack: string; // 파워팩
  powerSupply: string; // 사용 전원
  additionalOptions: string; // 추가 옵션
  isBrochure: boolean;
  isTechnicalData: boolean;
  accessories?: Accessory[];
};

export type Brand = {
  brandName: string;
  equipments: Equipment[];
};

export type CraneType = {
  type: string;
  brands: Brand[];
};

export const cranes: CraneType[] = [
  {
    type: "spider",
    brands: [
      {
        brandName: "Jekko",
        equipments: [
          {
            modelName: "SPX312",
            dimensions: "2790 x 770 x 1600mm",
            bodyWeight: "1915kg",
            dryWeight: "1800kg",
            counterWeight: "",
            maxSafeLoad: "1200kg",
            maxLiftingHeight: "7.6m",
            maxLiftingLength: "7.3m",
            maxHeightTipLoadWinch: "600kg",
            maxLengthTipLoadWinch: "300kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 75°",
            hoistingSpeed: "15.1 ~ 31.8m/min",
            slewingAngle: "330°",
            slewingSpeed: "1.0rpm",
            winchLength: "63m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "3700 x 3700mm",
            maxOutriggerLoad: "1850kg",
            trackDimensions: "770, (1065)mm",
            speed: "0.85km/h",
            climbingAbility: "20°",
            groundPressure: "0.44kg/㎠",
            operatingMethod: "배터리",
            powerType: "24V 240Ah\n(12V 120Ah) x 2\n24V - 3F 4.0kW 5.5HP",
            powerPack: "4.0kW 220VAC 50Hz",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "2790 x 770 x 1600mm",
                bodyWeight: "1915 + 85kg\n(2000kg)",
                dryWeight: "1800kg",
                counterWeight: "",
                maxSafeLoad: "1200kg",
                maxLiftingHeight: "9.8m",
                maxLiftingLength: "9.6m",
                maxHeightTipLoadWinch: "400kg",
                maxLengthTipLoadWinch: "100kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75°",
                hoistingSpeed: "15.1 ~ 31.8m/min",
                slewingAngle: "330°",
                slewingSpeed: "1.0rpm",
                winchLength: "63m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "3700 x 3700mm",
                maxOutriggerLoad: "1850kg",
                trackDimensions: "775, (1065)mm",
                speed: "0.85km/h",
                climbingAbility: "20°",
                groundPressure: "0.44kg/㎠",
                operatingMethod: "배터리",
                powerType: "24V 240Ah\n(12V 120Ah) x 2\n24V - 3F 4.0kW 5.5HP",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "400.1MX",
                accessoryType: "jib"
              }
            ]
          },
          {
            modelName: "SPX424",
            dimensions: "3165 x 775 x 1955mm",
            bodyWeight: "2195kg",
            dryWeight: "2080kg",
            counterWeight: "",
            maxSafeLoad: "2400kg",
            maxLiftingHeight: "8.5m",
            maxLiftingLength: "7.6m",
            maxHeightTipLoadWinch: "1000kg",
            maxLengthTipLoadWinch: "400kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 75°",
            hoistingSpeed: "26 ~ 31.8m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.5rpm",
            winchLength: "73m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "3730 x 3730mm",
            maxOutriggerLoad: "2200kg",
            trackDimensions: "775, (1100)mm",
            speed: "0.72km/h",
            climbingAbility: "20°",
            groundPressure: "0.55kg/㎠",
            operatingMethod: "배터리",
            powerType: "24V 240Ah\n24V - 3F 4.0kW 5.5HP",
            powerPack: "4.0kW 220VAC 50Hz",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "3165 x 775 x 1955mm",
                bodyWeight: "2195 + 170kg\n(2365kg)",
                dryWeight: "2080kg",
                counterWeight: "",
                maxSafeLoad: "2400kg",
                maxLiftingHeight: "13.49m",
                maxLiftingLength: "11.8m",
                maxHeightTipLoadWinch: "300kg",
                maxLengthTipLoadWinch: "110kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75°",
                hoistingSpeed: "26 ~ 31.8m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.5rpm",
                winchLength: "73m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "3730 x 3730mm",
                maxOutriggerLoad: "2200kg",
                trackDimensions: "775, (1100)mm",
                speed: "0.72km/h",
                climbingAbility: "20°",
                groundPressure: "0.55kg/㎠",
                operatingMethod: "배터리",
                powerType: "24V 240Ah\n24V - 3F 4.0kW 5.5HP",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB800.2H1MX",
                accessoryType: "jib"
              },
              {
                dimensions: "3165 x 775 x 1955mm",
                bodyWeight: "2195 + 295kg\n(2490kg)",
                dryWeight: "2080kg",
                counterWeight: "",
                maxSafeLoad: "10패드 800kg",
                maxLiftingHeight: "9.8m",
                maxLiftingLength: "7m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "700kg",
                maxLengthTipLoadHook: "140kg",
                workingAngle: "0° ~ 75°\n(↑90° ↓45°)\n(← 90° 90°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.5rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "3730 x 3730mm",
                maxOutriggerLoad: "2200kg",
                trackDimensions: "775, (1100)mm",
                speed: "0.72km/h",
                climbingAbility: "20°",
                groundPressure: "0.55kg/㎠",
                operatingMethod: "배터리",
                powerType: "24V 240Ah\n24V - 3F 4.0kW 5.5HP",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "MR800.4",
                accessoryType: "glass"
              }
            ]
          },
          {
            modelName: "SPX527",
            dimensions: "4145 x 1100 x 1957mm",
            bodyWeight: "3660kg",
            dryWeight: "3600kg",
            counterWeight: "",
            maxSafeLoad: "2700kg",
            maxLiftingHeight: "12.1m",
            maxLiftingLength: "11m",
            maxHeightTipLoadWinch: "1000kg",
            maxLengthTipLoadWinch: "250kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-2° ~ 80°",
            hoistingSpeed: "40.6m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "60m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4160 x 4160mm",
            maxOutriggerLoad: "2700kg",
            trackDimensions: "600, (1100)mm",
            speed: "2.0km/h",
            climbingAbility: "25°",
            groundPressure: "0.53kg/㎠",
            operatingMethod: "디젤(경유) 20L",
            powerType: "KUBOTA D1105-E3B\n(18.5kW 25HP)",
            powerPack: "4.0kW 220VAC 50Hz",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "4145 x 1100 x 1957mm",
                bodyWeight: "3660 + 215kg\n(3875kg)",
                dryWeight: "3600kg",
                counterWeight: "",
                maxSafeLoad: "2700kg",
                maxLiftingHeight: "16.3m",
                maxLiftingLength: "11m",
                maxHeightTipLoadWinch: "500kg",
                maxLengthTipLoadWinch: "190kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "-2° ~ 80°",
                hoistingSpeed: "40.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "60m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4160 x 4160mm",
                maxOutriggerLoad: "2700kg",
                trackDimensions: "600, (1100)mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.53kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA D1105-E3B\n(18.5kW 25HP)",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 600.2H",
                accessoryType: "jib"
              },
              {
                dimensions: "4145 x 1100 x 1957mm",
                bodyWeight: "3660 + 295kg\n(3955kg)",
                dryWeight: "3600kg",
                counterWeight: "",
                maxSafeLoad: "10패드 800kg",
                maxLiftingHeight: "13.4m",
                maxLiftingLength: "9m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "600kg",
                maxLengthTipLoadHook: "150kg",
                workingAngle: "-2° ~ 80°\n(↑90° ↓45°)\n(← 90° 90°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4160 x 4160mm",
                maxOutriggerLoad: "2700kg",
                trackDimensions: "600, (1100)mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.53kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA D1105-E3B\n(18.5kW 25HP)",
                powerPack: "4.0kW 220VAC 50Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "MR800.4",
                accessoryType: "glass"
              }
            ]
          },
          {
            modelName: "SPX328",
            dimensions: "2950 x 730 x 1610mm",
            bodyWeight: "2300kg",
            dryWeight: "2300kg",
            counterWeight: "",
            maxSafeLoad: "2800kg",
            maxLiftingHeight: "10.4m",
            maxLiftingLength: "8m",
            maxHeightTipLoadWinch: "1020kg",
            maxLengthTipLoadWinch: "250kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-4.5° ~ 77°",
            hoistingSpeed: "38 ~ 53m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.2rpm",
            winchLength: "62m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "3830 x 3865mm",
            maxOutriggerLoad: "2100kg",
            trackDimensions: "730mm",
            speed: "1.2km/h, (2.6km/h)",
            climbingAbility: "12°",
            groundPressure: "0.62kg/㎠",
            operatingMethod: "리튬 배터리",
            powerType: "48V 250Ah",
            powerPack: "",
            powerSupply: "1.0kW 220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "2950 x 730 x 1610mm",
                bodyWeight: "2420kg",
                dryWeight: "2300kg",
                counterWeight: "",
                maxSafeLoad: "2800kg",
                maxLiftingHeight: "12.8m",
                maxLiftingLength: "10.4m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "300kg",
                maxLengthTipLoadHook: "100kg",
                workingAngle: "-4.5° ~ 77°",
                hoistingSpeed: "38 ~ 53m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "62m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "3830 x 3865mm",
                maxOutriggerLoad: "2100kg",
                trackDimensions: "730mm",
                speed: "1.2km/h, (2.6km/h)",
                climbingAbility: "12°",
                groundPressure: "0.62kg/㎠",
                operatingMethod: "리튬 배터리",
                powerType: "48V 250Ah",
                powerPack: "",
                powerSupply: "1.0kW 220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "JIB 500.1EX",
                accessoryType: "jib"
              }
            ]
          },
          {
            modelName: "SPX532",
            dimensions: "3220 x 770 x 1950mm",
            bodyWeight: "2560kg",
            dryWeight: "2520kg",
            counterWeight: "200kg",
            maxSafeLoad: "3200kg",
            maxLiftingHeight: "12.1m",
            maxLiftingLength: "9.5m",
            maxHeightTipLoadWinch: "1450kg",
            maxLengthTipLoadWinch: "470kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 83°",
            hoistingSpeed: "40.6m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.2rpm",
            winchLength: "60m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "4400 x 4400mm",
            maxOutriggerLoad: "3000kg",
            trackDimensions: "770, (1050)mm",
            speed: "2.7km/h",
            climbingAbility: "20°",
            groundPressure: "0.63kg/㎠",
            operatingMethod: "리튬 배터리",
            powerType: "24V 300Ah\n(24V - 3F 5.5kW 7.5HP)",
            powerPack: "",
            powerSupply: "7.7kW 220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "3220 x 770 x 1950mm",
                bodyWeight: "2770kg",
                dryWeight: "2520kg",
                counterWeight: "200kg",
                maxSafeLoad: "3200kg",
                maxLiftingHeight: "17.3m",
                maxLiftingLength: "14.8m",
                maxHeightTipLoadWinch: "400kg",
                maxLengthTipLoadWinch: "100kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 83°",
                hoistingSpeed: "40.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "60m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "4400 x 4400mm",
                maxOutriggerLoad: "3000kg",
                trackDimensions: "770, (1050)mm",
                speed: "2.7km/h",
                climbingAbility: "20°",
                groundPressure: "0.63kg/㎠",
                operatingMethod: "리튬 배터리",
                powerType: "24V 300Ah\n(24V - 3F 5.5kW 7.5HP)",
                powerPack: "",
                powerSupply: "7.7kW 220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "JIB1000.2H1MX",
                accessoryType: "jib"
              },
              {
                dimensions: "3220 x 770 x 1950mm",
                bodyWeight: "2560 + 230kg\n(2790kg)",
                dryWeight: "2520kg",
                counterWeight: "",
                maxSafeLoad: "500kg",
                maxLiftingHeight: "13.6m",
                maxLiftingLength: "10m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "500kg",
                maxLengthTipLoadHook: "200kg",
                workingAngle: "0° ~ 83°\n(↑ 91° ↓ 92°)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4400 x 4400mm",
                maxOutriggerLoad: "3000kg",
                trackDimensions: "770, (1050)mm",
                speed: "2.7km/h",
                climbingAbility: "20°",
                groundPressure: "0.63kg/㎠",
                operatingMethod: "리튬 배터리",
                powerType: "24V 300Ah\n(24V - 3F 5.5kW 7.5HP)",
                powerPack: "",
                powerSupply: "7.7kW 220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "JIB500GR",
                accessoryType: "jib"
              }
            ]
          },
          {
            modelName: "SPX1040",
            dimensions: "5390 x 1450 x 2040mm",
            bodyWeight: "6400kg",
            dryWeight: "6300kg",
            counterWeight: "760kg",
            maxSafeLoad: "4000kg",
            maxLiftingHeight: "14.5m",
            maxLiftingLength: "13m",
            maxHeightTipLoadWinch: "1800kg",
            maxLengthTipLoadWinch: "550kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-4° ~ 80°",
            hoistingSpeed: "50.6m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "125m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4200 x 4200mm",
            maxOutriggerLoad: "4500kg",
            trackDimensions: "1450mm",
            speed: "2.0km/h",
            climbingAbility: "25°",
            groundPressure: "0.59kg/㎠",
            operatingMethod: "디젤(경유) 20L",
            powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
            powerPack: "8.0kW 220VAC 60Hz",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "5390 x 1450 x 2040mm",
                bodyWeight: "6400 + 210kg\n(6610kg)",
                dryWeight: "6300kg",
                counterWeight: "760kg",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "18.6m",
                maxLiftingLength: "13m",
                maxHeightTipLoadWinch: "900kg",
                maxLengthTipLoadWinch: "100kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "-4° ~ 80°",
                hoistingSpeed: "50.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "125m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "1450mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.59kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
                powerPack: "8.0kW 220VAC 60Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 600.2H",
                accessoryType: "jib"
              },
              {
                dimensions: "5390 x 1450 x 2040mm",
                bodyWeight: "6400 + 70kg\n(6470kg)",
                dryWeight: "6300kg",
                counterWeight: "760kg",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "16.1m",
                maxLiftingLength: "14.5m",
                maxHeightTipLoadWinch: "1600kg",
                maxLengthTipLoadWinch: "300kg",
                maxHeightTipLoadHook: "1600kg",
                maxLengthTipLoadHook: "300kg",
                workingAngle: "-4° ~ 80°",
                hoistingSpeed: "50.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "125m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "1450mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.59kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
                powerPack: "8.0kW 220VAC 60Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 3500G",
                accessoryType: "jib"
              },
              {
                dimensions: "5390 x 1450 x 2040mm",
                bodyWeight: "6400 + 210kg\n(6610kg)",
                dryWeight: "6300kg",
                counterWeight: "760kg",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "23.5m",
                maxLiftingLength: "13m",
                maxHeightTipLoadWinch: "800kg",
                maxLengthTipLoadWinch: "300kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "-4° ~ 80°",
                hoistingSpeed: "50.6m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "125m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4200 x 4200mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "1450mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.59kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
                powerPack: "8.0kW 220VAC 60Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 100.1FL",
                accessoryType: "jib"
              },
              {
                dimensions: "5390 x 1450 x 2040mm",
                bodyWeight: "6400 + 295kg\n(6695kg)",
                dryWeight: "6300kg",
                counterWeight: "760kg",
                maxSafeLoad: "800kg",
                maxLiftingHeight: "16.3m",
                maxLiftingLength: "13m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "800kg",
                maxLengthTipLoadHook: "150kg",
                workingAngle: "-4° ~ 80°\n(↑90° ↓45°)\n(← 90° 90°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4200 x 4200mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "1450mm",
                speed: "2.0km/h",
                climbingAbility: "25°",
                groundPressure: "0.59kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA 01105-E3B\n(18.5 kW 25.0 Hp)",
                powerPack: "8.0kW 220VAC 60Hz",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "MR800.4",
                accessoryType: "glass"
              }
            ]
          },
          {
            modelName: "SPX650",
            dimensions: "4460 x 980 x 2020mm",
            bodyWeight: "5960kg",
            dryWeight: "5900kg",
            counterWeight: "",
            maxSafeLoad: "5000kg",
            maxLiftingHeight: "17.3m",
            maxLiftingLength: "14m",
            maxHeightTipLoadWinch: "2000kg",
            maxLengthTipLoadWinch: "600kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 82°",
            hoistingSpeed: "25 ~ 33m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "90m",
            winchDiameter: "⌀7mm",
            outriggerExtensionDimensions: "4510 x 4510mm",
            maxOutriggerLoad: "4800kg",
            trackDimensions: "980, (1380)mm",
            speed: "1.9km/h, (2.9km/h)",
            climbingAbility: "20°",
            groundPressure: "0.75kg/㎠",
            operatingMethod: "배터리",
            powerType: "",
            powerPack: "",
            powerSupply: "16kW 220VAC 60Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "4460 x 980 x 2020mm",
                bodyWeight: "5960 + 40kg\n(6000kg)",
                dryWeight: "5900kg",
                counterWeight: "",
                maxSafeLoad: "5000kg",
                maxLiftingHeight: "18.6m",
                maxLiftingLength: "14.95m",
                maxHeightTipLoadWinch: "2000kg",
                maxLengthTipLoadWinch: "450kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 82°",
                hoistingSpeed: "25 ~ 33m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "90m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "4510 x 4510mm",
                maxOutriggerLoad: "4800kg",
                trackDimensions: "980, (1380)mm",
                speed: "1.9km/h, (2.9km/h)",
                climbingAbility: "20°",
                groundPressure: "0.75kg/㎠",
                operatingMethod: "배터리",
                powerType: "",
                powerPack: "",
                powerSupply: "16kW 220VAC 60Hz",
                additionalOptions: "",
                accessoryName: "JIB 2000GX",
                accessoryType: "jib"
              },
              {
                dimensions: "4460 x 980 x 2020mm",
                bodyWeight: "5960 + 410kg\n(6370kg)",
                dryWeight: "5900kg",
                counterWeight: "",
                maxSafeLoad: "5000kg",
                maxLiftingHeight: "23.6m",
                maxLiftingLength: "20m",
                maxHeightTipLoadWinch: "800kg",
                maxLengthTipLoadWinch: "150kg",
                maxHeightTipLoadHook: "800kg",
                maxLengthTipLoadHook: "150kg",
                workingAngle: "0° ~ 82°",
                hoistingSpeed: "25 ~ 33m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "90m",
                winchDiameter: "⌀7mm",
                outriggerExtensionDimensions: "4510 x 4510mm",
                maxOutriggerLoad: "4800kg",
                trackDimensions: "980, (1380)mm",
                speed: "1.9km/h, (2.9km/h)",
                climbingAbility: "20°",
                groundPressure: "0.75kg/㎠",
                operatingMethod: "배터리",
                powerType: "",
                powerPack: "",
                powerSupply: "16kW 220VAC 60Hz",
                additionalOptions: "",
                accessoryName: "JIB 1200 3HX",
                accessoryType: "jib"
              },
              {
                dimensions: "4460 x 980 x 2020mm",
                bodyWeight: "5960 + 230kg\n(6190kg)",
                dryWeight: "5900kg",
                counterWeight: "",
                maxSafeLoad: "500kg",
                maxLiftingHeight: "17.2m",
                maxLiftingLength: "15.75m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "500kg",
                maxLengthTipLoadHook: "240kg",
                workingAngle: "0° ~ 82°\n(↑ 91° ↓ 92°)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4510 x 4510mm",
                maxOutriggerLoad: "4800kg",
                trackDimensions: "980, (1380)mm",
                speed: "1.9km/h, (2.9km/h)",
                climbingAbility: "20°",
                groundPressure: "0.75kg/㎠",
                operatingMethod: "배터리",
                powerType: "",
                powerPack: "",
                powerSupply: "16kW 220VAC 60Hz",
                additionalOptions: "",
                accessoryName: "JIB500GR",
                accessoryType: "grapple"
              }
            ]
          },
          {
            modelName: "JF545",
            dimensions: "5450 x 1840 x 2750mm",
            bodyWeight: "17400kg",
            dryWeight: "17250kg",
            counterWeight: "3500kg",
            maxSafeLoad: "15.500kg",
            maxLiftingHeight: "19m",
            maxLiftingLength: "16.15m",
            maxHeightTipLoadWinch: "3900kg",
            maxLengthTipLoadWinch: "2010kg",
            maxHeightTipLoadHook: "4450kg",
            maxLengthTipLoadHook: "2500kg",
            workingAngle: "-15° ~ 80°",
            hoistingSpeed: "36.5 ~ 47m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "60m",
            winchDiameter: "⌀12mm",
            outriggerExtensionDimensions: "6700 x 6700mm",
            maxOutriggerLoad: "11250kg",
            trackDimensions: "1840mm",
            speed: "2.5km/h",
            climbingAbility: "30°",
            groundPressure: "0.85kg/㎠",
            operatingMethod: "디젤(경유) 20L",
            powerType: "KUBOTA\nV3307-CR-TE4B\n(55,4kW 74HP)",
            powerPack: "",
            powerSupply: "13kW 400VAC 60Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "5450 x 1840 x 2750mm",
                bodyWeight: "17400 + 1260kg\n(18660kg)",
                dryWeight: "17250kg",
                counterWeight: "3500kg",
                maxSafeLoad: "15.500kg",
                maxLiftingHeight: "30.6m",
                maxLiftingLength: "28.30m",
                maxHeightTipLoadWinch: "250kg",
                maxLengthTipLoadWinch: "305kg",
                maxHeightTipLoadHook: "500kg",
                maxLengthTipLoadHook: "600kg",
                workingAngle: "-15° ~ 80°",
                hoistingSpeed: "36.5 ~ 47m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "60m",
                winchDiameter: "⌀12mm",
                outriggerExtensionDimensions: "6700 x 6700mm",
                maxOutriggerLoad: "11250kg",
                trackDimensions: "1840mm",
                speed: "2.5km/h",
                climbingAbility: "30°",
                groundPressure: "0.85kg/㎠",
                operatingMethod: "디젤(경유) 20L",
                powerType: "KUBOTA\nV3307-CR-TE4B\n(55,4kW 74HP)",
                powerPack: "",
                powerSupply: "13kW 400VAC 60Hz",
                additionalOptions: "MWP-2PGR\n(바구니)",
                accessoryName: "JIB 3000.6HA",
                accessoryType: "jib"
              }
            ]
          }
        ]
      },
      {
        brandName: "Hoeflon",
        equipments: [
          {
            modelName: "C1",
            dimensions: "1750 x 700 x 1260mm",
            bodyWeight: "1060kg",
            dryWeight: "960kg",
            counterWeight: "290kg",
            maxSafeLoad: "550kg",
            maxLiftingHeight: "4.4m",
            maxLiftingLength: "3.3m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "490kg",
            maxLengthTipLoadHook: "190kg",
            workingAngle: "-5° ~ 75°",
            hoistingSpeed: "",
            slewingAngle: "136°",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "1478 x 1100mm",
            maxOutriggerLoad: "",
            trackDimensions: "700, (1000)mm",
            speed: "0.5km/h, (1.1km/h)",
            climbingAbility: "22°",
            groundPressure: "0.28kg/㎠",
            operatingMethod: "배터리",
            powerType: "",
            powerPack: "",
            powerSupply: "230V 60Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "1750 x 700 x 1260mm",
                bodyWeight: "1060kg",
                dryWeight: "960kg",
                counterWeight: "290kg",
                maxSafeLoad: "550kg",
                maxLiftingHeight: "5.7m",
                maxLiftingLength: "4.6m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "470kg",
                maxLengthTipLoadHook: "120kg",
                workingAngle: "-5° ~ 75°",
                hoistingSpeed: "",
                slewingAngle: "136°",
                slewingSpeed: "",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "1478 x 1100mm",
                maxOutriggerLoad: "",
                trackDimensions: "700, (1000)mm",
                speed: "0.5km/h, (1.1km/h)",
                climbingAbility: "22°",
                groundPressure: "0.28kg/㎠",
                operatingMethod: "배터리",
                powerType: "",
                powerPack: "",
                powerSupply: "230V 60Hz",
                additionalOptions: "",
                accessoryName: "FLY JIB",
                accessoryType: "jib"
              }
            ]
          },
          {
            modelName: "C6",
            dimensions: "3140 x 750 x 1950mm",
            bodyWeight: "2650kg",
            dryWeight: "2630kg",
            counterWeight: "600kg",
            maxSafeLoad: "3000kg",
            maxLiftingHeight: "11.5m",
            maxLiftingLength: "9.2m",
            maxHeightTipLoadWinch: "900kg",
            maxLengthTipLoadWinch: "470kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 75°",
            hoistingSpeed: "20.8m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.5rpm",
            winchLength: "50m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4200 x 4400mm",
            maxOutriggerLoad: "2800kg",
            trackDimensions: "750, (1050)mm",
            speed: "1.1km/h, (2.2km/h)",
            climbingAbility: "20°",
            groundPressure: "0.79kg/㎠",
            operatingMethod: "리튬 배터리\n디젤(경유) 20L",
            powerType: "(C6) Yanmar 3-cylinder diesel\n(C6e) 80 V Lithium\n(9.5kW 12.7HP)",
            powerPack: "",
            powerSupply: "220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                dimensions: "3140 x 750 x 1950mm",
                bodyWeight: "2650 + 200kg\n(2850kg)",
                dryWeight: "2630kg",
                counterWeight: "600kg",
                maxSafeLoad: "3000kg",
                maxLiftingHeight: "16.4m",
                maxLiftingLength: "13.7m",
                maxHeightTipLoadWinch: "601kg",
                maxLengthTipLoadWinch: "210kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75°",
                hoistingSpeed: "20.8m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.5rpm",
                winchLength: "50m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4200 x 4400mm",
                maxOutriggerLoad: "2800kg",
                trackDimensions: "750, (1050)mm",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                groundPressure: "0.79kg/㎠",
                operatingMethod: "리튬 배터리\n디젤(경유) 20L",
                powerType: "(C6) Yanmar 3-cylinder diesel\n(C6e) 80 V Lithium\n(9.5kW 12.7HP)",
                powerPack: "",
                powerSupply: "220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "FLY JIB",
                accessoryType: "jib"
              },
              {
                dimensions: "3140 x 750 x 1950mm",
                bodyWeight: "2650 + 340kg\n(2990kg)",
                dryWeight: "2630kg",
                counterWeight: "",
                maxSafeLoad: "1250kg",
                maxLiftingHeight: "13.7m",
                maxLiftingLength: "11.4m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "680kg",
                maxLengthTipLoadHook: "120kg",
                workingAngle: "0° ~ 75°\n(↑103° ~ ↓100°)\n(← 45° 50°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.5rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4200 x 4400mm",
                maxOutriggerLoad: "2800kg",
                trackDimensions: "750, (1050)mm",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                groundPressure: "0.79kg/㎠",
                operatingMethod: "리튬 배터리\n디젤(경유) 20L",
                powerType: "(C6) Yanmar 3-cylinder diesel\n(C6e) 80 V Lithium\n(9.5kW 12.7HP)",
                powerPack: "",
                powerSupply: "220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "MC1200",
                accessoryType: "grapple"
              }
            ]
          },
          {
            modelName: "C10",
            dimensions: "4150 x 800 x 2070mm",
            bodyWeight: "4500kg",
            dryWeight: "4400kg",
            counterWeight: "1340kg",
            maxSafeLoad: "4000kg",
            maxLiftingHeight: "16.3m",
            maxLiftingLength: "13.5m",
            maxHeightTipLoadWinch: "2070kg",
            maxLengthTipLoadWinch: "430kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-5° ~ 83°",
            hoistingSpeed: "20.8m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "60m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4578 x 4578mm",
            maxOutriggerLoad: "4500kg",
            trackDimensions: "800, (1100)mm",
            speed: "1.1km/h, (2.2km/h)",
            climbingAbility: "20°",
            groundPressure: "0.72kg/㎠",
            operatingMethod: "리튬 배터리\n디젤(경유) 20L",
            powerType: "Yanmar 3 cylinder 7.3 kW\n80 V 163 Ah LiFePO₄\n(13kW 14.1HP)",
            powerPack: "",
            powerSupply: "220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                dimensions: "4150 x 800 x 2070mm",
                bodyWeight: "4500 + 200kg\n(4700kg)",
                dryWeight: "4400kg",
                counterWeight: "1340kg",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "22m",
                maxLiftingLength: "19.8m",
                maxHeightTipLoadWinch: "710kg",
                maxLengthTipLoadWinch: "198kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "-5° ~ 83°",
                hoistingSpeed: "20.8m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "60m",
                winchDiameter: "⌀8mm",
                outriggerExtensionDimensions: "4578 x 4578mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "800, (1100)mm",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                groundPressure: "0.72kg/㎠",
                operatingMethod: "리튬 배터리\n디젤(경유) 20L",
                powerType: "Yanmar 3 cylinder 7.3 kW\n80 V 163 Ah LiFePO₄\n(13kW 14.1HP)",
                powerPack: "",
                powerSupply: "220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "FLY JIB",
                accessoryType: "jib"
              },
              {
                dimensions: "4150 x 800 x 2070mm",
                bodyWeight: "4500 + 340kg\n(4840kg)",
                dryWeight: "4400kg",
                counterWeight: "",
                maxSafeLoad: "4000kg",
                maxLiftingHeight: "18.5m",
                maxLiftingLength: "15.7m",
                maxHeightTipLoadWinch: "",
                maxLengthTipLoadWinch: "",
                maxHeightTipLoadHook: "1200kg",
                maxLengthTipLoadHook: "100kg",
                workingAngle: "-5° ~ 83°\n(↑103° ~ ↓100°)\n(← 45° 50°→)",
                hoistingSpeed: "",
                slewingAngle: "360°",
                slewingSpeed: "1.0rpm",
                winchLength: "",
                winchDiameter: "",
                outriggerExtensionDimensions: "4578 x 4578mm",
                maxOutriggerLoad: "4500kg",
                trackDimensions: "800, (1100)mm",
                speed: "1.1km/h, (2.2km/h)",
                climbingAbility: "20°",
                groundPressure: "0.72kg/㎠",
                operatingMethod: "리튬 배터리\n디젤(경유) 20L",
                powerType: "Yanmar 3 cylinder 7.3 kW\n80 V 163 Ah LiFePO₄\n(13kW 14.1HP)",
                powerPack: "",
                powerSupply: "220VAC 50Hz",
                additionalOptions: "",
                accessoryName: "MC1200",
                accessoryType: "grapple"
              }
            ]
          }
        ]
      },
      {
        brandName: "BEFARD",
        equipments: [
          {
            modelName: "XM800",
            dimensions: "2250 x 780 x 1460mm",
            bodyWeight: "1150kg",
            dryWeight: "1050kg",
            counterWeight: "102kg\n(5.8kg x 12)",
            maxSafeLoad: "800kg",
            maxLiftingHeight: "4.6m",
            maxLiftingLength: "3.5m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "455kg",
            maxLengthTipLoadHook: "280kg",
            workingAngle: "0° ~ 65°",
            hoistingSpeed: "20.8m/min",
            slewingAngle: "50°",
            slewingSpeed: "",
            winchLength: "50m",
            winchDiameter: "⌀6mm",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "780, (1100)mm",
            speed: "2.2km/h",
            climbingAbility: "25°",
            groundPressure: "",
            operatingMethod: "리튬 배터리",
            powerType: "48V 80Ah",
            powerPack: "",
            powerSupply: "220VAC 50Hz",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "XGR800",
            dimensions: "2800 x 930 x 1600mm",
            bodyWeight: "1600kg",
            dryWeight: "",
            counterWeight: "616kg\n(5kg x 40장)\n(16kg x 26장)",
            maxSafeLoad: "800kg",
            maxLiftingHeight: "5.5m",
            maxLiftingLength: "3.7m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "350kg",
            maxLengthTipLoadHook: "420kg",
            workingAngle: "0° ~ 65°\n(↑95° ↓90°)\n(← 90° 90°→)",
            hoistingSpeed: "",
            slewingAngle: "",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "930mm",
            speed: "2.2km/h",
            climbingAbility: "25°",
            groundPressure: "",
            operatingMethod: "리튬 배터리",
            powerType: "230V 50Hz",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: false,
            isTechnicalData: false
          }
        ]
      },
      {
        brandName: "UNIC",
        equipments: [
          {
            modelName: "URW295",
            dimensions: "2730 x 600 x 1430mm",
            bodyWeight: "2040kg",
            dryWeight: "1850kg",
            counterWeight: "",
            maxSafeLoad: "2900kg",
            maxLiftingHeight: "8.8m",
            maxLiftingLength: "8.65m",
            maxHeightTipLoadWinch: "650kg",
            maxLengthTipLoadWinch: "130kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "10 ~ 40m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.5rpm",
            winchLength: "54m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "3885 x 3935mm",
            maxOutriggerLoad: "",
            trackDimensions: "600mm",
            speed: "2.0km/h",
            climbingAbility: "20°",
            groundPressure: "0.48kg/㎠",
            operatingMethod: "가솔린(휘발유) 6L",
            powerType: "",
            powerPack: "3.7kW 220V 3상 4P",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "URW546",
            dimensions: "4870 x 1380 x 2035mm",
            bodyWeight: "4940kg",
            dryWeight: "4920kg",
            counterWeight: "",
            maxSafeLoad: "4000kg",
            maxLiftingHeight: "16m",
            maxLiftingLength: "15.52m",
            maxHeightTipLoadWinch: "860kg",
            maxLengthTipLoadWinch: "160kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "10 ~ 40m/min",
            slewingAngle: "360°",
            slewingSpeed: "2.5rpm",
            winchLength: "103m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "5900 x 5940mm",
            maxOutriggerLoad: "",
            trackDimensions: "1380mm",
            speed: "3.0km/h",
            climbingAbility: "23°",
            groundPressure: "0.47kg/㎠",
            operatingMethod: "디젤(경유) 40L",
            powerType: "Yanmar 3TNV80F\n(15.2kW 20.4HP)",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "RC 무선 조종기",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "URW547",
            dimensions: "4955 x 1380 x 1980mm",
            bodyWeight: "5170kg",
            dryWeight: "5010kg",
            counterWeight: "",
            maxSafeLoad: "4000kg",
            maxLiftingHeight: "18.2m",
            maxLiftingLength: "17.83m",
            maxHeightTipLoadWinch: "300kg",
            maxLengthTipLoadWinch: "50kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "10 ~ 40m/min",
            slewingAngle: "360°",
            slewingSpeed: "2.5rpm",
            winchLength: "103m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "5900 x 5940mm",
            maxOutriggerLoad: "",
            trackDimensions: "1380mm",
            speed: "3.0km/h",
            climbingAbility: "23°",
            groundPressure: "0.48kg/㎠",
            operatingMethod: "디젤(경유) 40L",
            powerType: "Yanmar 3TNV80F\n(15.2kW 20.4HP)",
            powerPack: "입력 380V 출력 220V\n3상 4P 7.5kW",
            powerSupply: "",
            additionalOptions:
              "KM - 100 중량초과 자동 정지 장치\n디지털 인양중량 미터기\n무선 조종기\n- C4A, C2A -\nSLI(인양 무게 인디케이터) 무선 조종기\n- C4E,C2E -\nC4E + 파워팩\n-C4EM-\n단선용 후크\n-ALL-",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "URW706",
            dimensions: "5610 x 1670 x 2185mm",
            bodyWeight: "7990kg",
            dryWeight: "7920kg",
            counterWeight: "",
            maxSafeLoad: "6000kg",
            maxLiftingHeight: "19.5m",
            maxLiftingLength: "18.6m",
            maxHeightTipLoadWinch: "1350kg",
            maxLengthTipLoadWinch: "200kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "10 ~ 40m/min",
            slewingAngle: "360°",
            slewingSpeed: "2.5rpm",
            winchLength: "111m",
            winchDiameter: "⌀10mm",
            outriggerExtensionDimensions: "6550 x 6460mm",
            maxOutriggerLoad: "",
            trackDimensions: "1670mm",
            speed: "3.0km/h",
            climbingAbility: "23°",
            groundPressure: "0.44kg/㎠",
            operatingMethod: "디젤(경유) 60L",
            powerType: "Kubota D7103-M-DI-E4B\n(18.5kW 24.81HP)",
            powerPack: "입력 380V 출력 220V\n3상 4P 7.5kW",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false,
            accessories: [
              {
                dimensions: "5610 x 1670 x 2185mm",
                bodyWeight: "7990 + 205kg\n(8195kg)",
                dryWeight: "7920kg",
                counterWeight: "",
                maxSafeLoad: "6000kg",
                maxLiftingHeight: "22.615m",
                maxLiftingLength: "18.6m",
                maxHeightTipLoadWinch: "800kg",
                maxLengthTipLoadWinch: "300kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 80°",
                hoistingSpeed: "10 ~ 40m/min",
                slewingAngle: "360°",
                slewingSpeed: "2.5rpm",
                winchLength: "111m",
                winchDiameter: "⌀10mm",
                outriggerExtensionDimensions: "6550 x 6460mm",
                maxOutriggerLoad: "",
                trackDimensions: "1670mm",
                speed: "3.0km/h",
                climbingAbility: "23°",
                groundPressure: "0.44kg/㎠",
                operatingMethod: "디젤(경유) 60L",
                powerType: "Kubota D7103-M-DI-E4B\n(18.5kW 24.81HP)",
                powerPack: "입력 380V 출력 220V\n3상 4P 7.5kW",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "FLY JIB",
                accessoryType: "jib"
              },
              {
                dimensions: "5610 x 1670 x 2185mm",
                bodyWeight: "7990 + 480kg\n(8470kg)",
                dryWeight: "7920kg",
                counterWeight: "",
                maxSafeLoad: "6000kg",
                maxLiftingHeight: "25.9m",
                maxLiftingLength: "18.6m",
                maxHeightTipLoadWinch: "800kg",
                maxLengthTipLoadWinch: "150kg",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 80°",
                hoistingSpeed: "10 ~ 40m/min",
                slewingAngle: "360°",
                slewingSpeed: "2.5rpm",
                winchLength: "111m",
                winchDiameter: "⌀10mm",
                outriggerExtensionDimensions: "6550 x 6460mm",
                maxOutriggerLoad: "",
                trackDimensions: "1670mm",
                speed: "3.0km/h",
                climbingAbility: "23°",
                groundPressure: "0.44kg/㎠",
                operatingMethod: "디젤(경유) 60L",
                powerType: "Kubota D7103-M-DI-E4B\n(18.5kW 24.81HP)",
                powerPack: "입력 380V 출력 220V\n3상 4P 7.5kW",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "유압 지브",
                accessoryType: "jib"
              }
            ]
          }
        ]
      },
      {
        brandName: "MAEDA",
        equipments: [
          {
            modelName: "MC305",
            dimensions: "4285 x 1280 x 1695mm",
            bodyWeight: "4080kg",
            dryWeight: "3900kg",
            counterWeight: "",
            maxSafeLoad: "2980kg",
            maxLiftingHeight: "12.5m",
            maxLiftingLength: "12.485m",
            maxHeightTipLoadWinch: "790kg",
            maxLengthTipLoadWinch: "260kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "54m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.0rpm",
            winchLength: "73m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "4890 x 4505mm",
            maxOutriggerLoad: "1010kg",
            trackDimensions: "1280mm",
            speed: "2.8km/h",
            climbingAbility: "23°",
            groundPressure: "0.37kg/㎠",
            operatingMethod: "디젤(경유) 40L",
            powerType: "Yanmar 3TNV76\n(15.2kW 20.4HP)",
            powerPack: "380V 4P 5.5kW",
            powerSupply: "",
            additionalOptions: "파워팩\n(CE-2)\n단선용 후크\n전자식 작업 인디케이터\n-ALL-",
            isBrochure: true,
            isTechnicalData: false
          },
          {
            modelName: "MC405",
            dimensions: "4980 x 1380 x 1980mm",
            bodyWeight: "5750kg",
            dryWeight: "5600kg",
            counterWeight: "",
            maxSafeLoad: "3830kg",
            maxLiftingHeight: "16.8m",
            maxLiftingLength: "16.475m",
            maxHeightTipLoadWinch: "1130kg",
            maxLengthTipLoadWinch: "210kg",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "54m/min",
            slewingAngle: "330°",
            slewingSpeed: "2.5rpm",
            winchLength: "92m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "5790 x 5520mm",
            maxOutriggerLoad: "1400kg",
            trackDimensions: "1380mm",
            speed: "3.3km/h",
            climbingAbility: "20°",
            groundPressure: "0.50kg/㎠",
            operatingMethod: "디젤(경유) 60L",
            powerType: "Yanmar 3TNV88\n(17.5kW 23.5HP)",
            powerPack: "380V 3P 7.5kW",
            powerSupply: "",
            additionalOptions: "파워팩\n(CE)\n단선용 후크\n전자식 작업 인디케이터\n-ALL-",
            isBrochure: true,
            isTechnicalData: false
          }
        ]
      }
    ]
  },
  {
    type: "crawler",
    brands: [
      {
        brandName: "MAEDA",
        equipments: [
          {
            modelName: "LC383",
            dimensions: "4020 x 1740 x 2495mm",
            bodyWeight: "4040kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "2930kg",
            maxLiftingHeight: "8.71m(정차)\n5.03m(주행)",
            maxLiftingLength: "8.38m (정차)\n4.7m (주행)",
            maxHeightTipLoadWinch: "1190kg(정차)\n1465kg(주행)",
            maxLengthTipLoadWinch: "200kg(정차)\n230kg(주행)",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 80°",
            hoistingSpeed: "54m/min",
            slewingAngle: "330°",
            slewingSpeed: "1.0rpm",
            winchLength: "73m",
            winchDiameter: "⌀8mm",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "1740mm",
            speed: "2.9km/h, (4.6km/h)",
            climbingAbility: "20°",
            groundPressure: "0.44kg/㎠",
            operatingMethod: "디젤(경유) 42L",
            powerType: "Yanmar 3TNV88\n(21.5kW 28.8HP)",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false
          }
        ]
      },
      {
        brandName: "Kobelco",
        equipments: [
          {
            modelName: "CK120UR",
            dimensions: "5480 x 2490 x 2810mm",
            bodyWeight: "12470kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "4900kg",
            maxLiftingHeight: "14.77m(정차)\n9.51m(주행)",
            maxLiftingLength: "14.01m (정차)\n8.75m (주행)",
            maxHeightTipLoadWinch: "1400kg(정차)\n1400kg(주행)",
            maxLengthTipLoadWinch: "500kg(정차)\n550kg(주행)",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "-1° ~ 80°",
            hoistingSpeed: "44m/min",
            slewingAngle: "360°",
            slewingSpeed: "2.5rpm",
            winchLength: "113m",
            winchDiameter: "⌀10mm",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "2490mm",
            speed: "1.9km/h, (3.2km/h)",
            climbingAbility: "20°",
            groundPressure: "0.43kg/㎠",
            operatingMethod: "디젤(경유) 95L",
            powerType: "Isuzu 4LE2XDPC\n(41kW 55HP)",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: false
          }
        ]
      },
      {
        brandName: "Jekko",
        equipments: [
          {
            modelName: "SPK60",
            dimensions: "3505 x 2320 x 2640mm",
            bodyWeight: "13760kg",
            dryWeight: "",
            counterWeight: "1560kg",
            maxSafeLoad: "6000kg",
            maxLiftingHeight: "17.7m(정차)\n10.6m(주행)",
            maxLiftingLength: "17.1m(정차)\n10m(주행)",
            maxHeightTipLoadWinch: "1320kg(정차)\n850kg(주행)",
            maxLengthTipLoadWinch: "250kg(정차)\n450kg(주행)",
            maxHeightTipLoadHook: "",
            maxLengthTipLoadHook: "",
            workingAngle: "0° ~ 75° (정차)\n0° ~ 65° (주행)",
            hoistingSpeed: "30 ~ 55m/min",
            slewingAngle: "360°",
            slewingSpeed: "1.2rpm",
            winchLength: "125m",
            winchDiameter: "⌀10mm",
            outriggerExtensionDimensions: "",
            maxOutriggerLoad: "",
            trackDimensions: "2320, (2920)mm",
            speed: "1.7km/h (3.1km/h)",
            climbingAbility: "10°",
            groundPressure: "0.9kg/㎠",
            operatingMethod: "디젤(경유) 105L",
            powerType: "Yanmar 4TNV98T\n(53.7kW 73HP)",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: true,
            isTechnicalData: true,
            accessories: [
              {
                dimensions: "3505 x 2320 x 2640mm",
                bodyWeight: "13760 + 674kg\n(14434kg)",
                dryWeight: "",
                counterWeight: "1560kg",
                maxSafeLoad: "6000kg",
                maxLiftingHeight: "25.2m(정차)",
                maxLiftingLength: "12m(정차)",
                maxHeightTipLoadWinch: "490kg(정차)",
                maxLengthTipLoadWinch: "110kg(정차)",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75°",
                hoistingSpeed: "30 ~ 55m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "125m",
                winchDiameter: "⌀10mm",
                outriggerExtensionDimensions: "",
                maxOutriggerLoad: "",
                trackDimensions: "2320, (2920)mm",
                speed: "1.7km/h (3.1km/h)",
                climbingAbility: "10°",
                groundPressure: "0.9kg/㎠",
                operatingMethod: "디젤(경유) 105L",
                powerType: "Yanmar 4TNV98T\n(53.7kW 73HP)",
                powerPack: "",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 1501.3HL",
                accessoryType: "jib"
              },
              {
                dimensions: "3505 x 2320 x 2640mm",
                bodyWeight: "13760 + 70kg\n(13830kg)",
                dryWeight: "",
                counterWeight: "1560kg",
                maxSafeLoad: "6000kg",
                maxLiftingHeight: "19.2m(정차)\n11.9m(주행)",
                maxLiftingLength: "18.6m(정차)\n11m(주행)",
                maxHeightTipLoadWinch: "1330kg(정차)\n600kg(정차)",
                maxLengthTipLoadWinch: "150kg(정차)\n250kg(주행)",
                maxHeightTipLoadHook: "",
                maxLengthTipLoadHook: "",
                workingAngle: "0° ~ 75° (정차)\n0° ~ 65° (주행)",
                hoistingSpeed: "30 ~ 55m/min",
                slewingAngle: "360°",
                slewingSpeed: "1.2rpm",
                winchLength: "125m",
                winchDiameter: "⌀10mm",
                outriggerExtensionDimensions: "",
                maxOutriggerLoad: "",
                trackDimensions: "2320, (2920)mm",
                speed: "1.7km/h (3.1km/h)",
                climbingAbility: "10°",
                groundPressure: "0.9kg/㎠",
                operatingMethod: "디젤(경유) 105L",
                powerType: "Yanmar 4TNV98T\n(53.7kW 73HP)",
                powerPack: "",
                powerSupply: "",
                additionalOptions: "",
                accessoryName: "JIB 3500GX",
                accessoryType: "jib"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    type: "boom-lift",
    brands: [
      {
        brandName: "Cela",
        equipments: [
          {
            modelName: "DT15",
            dimensions: "4020 x 1740 x 2495mm",
            bodyWeight: "1550kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "200kg",
            maxLiftingHeight: "15m",
            maxLiftingLength: "7.5m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "200kg",
            maxLengthTipLoadHook: "200kg",
            workingAngle: "",
            hoistingSpeed: "",
            slewingAngle: "720°",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "4100 x 3400mm",
            maxOutriggerLoad: "",
            trackDimensions: "800mm",
            speed: "1.5km/h",
            climbingAbility: "",
            groundPressure: "",
            operatingMethod: "",
            powerType: "",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: false,
            isTechnicalData: true
          },
          {
            modelName: "DT25",
            dimensions: "5480 x 2490 x 2810mm",
            bodyWeight: "2950kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "230kg",
            maxLiftingHeight: "25m",
            maxLiftingLength: "12m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "230kg",
            maxLengthTipLoadHook: "230kg",
            workingAngle: "",
            hoistingSpeed: "",
            slewingAngle: "720°",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "4815 x 3600mm",
            maxOutriggerLoad: "",
            trackDimensions: "1150mm",
            speed: "1.5km/h",
            climbingAbility: "",
            groundPressure: "",
            operatingMethod: "",
            powerType: "",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: false,
            isTechnicalData: true
          },
          {
            modelName: "DT30",
            dimensions: "3505 x 2320 x 2640mm",
            bodyWeight: "5000kg",
            dryWeight: "",
            counterWeight: "",
            maxSafeLoad: "225kg",
            maxLiftingHeight: "30.20m",
            maxLiftingLength: "16m",
            maxHeightTipLoadWinch: "",
            maxLengthTipLoadWinch: "",
            maxHeightTipLoadHook: "225kg",
            maxLengthTipLoadHook: "225kg",
            workingAngle: "",
            hoistingSpeed: "",
            slewingAngle: "360°",
            slewingSpeed: "",
            winchLength: "",
            winchDiameter: "",
            outriggerExtensionDimensions: "5880 x 4280mm",
            maxOutriggerLoad: "",
            trackDimensions: "1200mm",
            speed: "1.5km/h",
            climbingAbility: "",
            groundPressure: "",
            operatingMethod: "",
            powerType: "",
            powerPack: "",
            powerSupply: "",
            additionalOptions: "",
            isBrochure: false,
            isTechnicalData: true
          }
        ]
      }
    ]
  }
];
